### ISSUE TITLE
PDF viewer not working with shared links

### ISSUE THREAD

**Issue by Winterkeks** [nextcloud/files_pdfviewer#1063]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Update on Nextcloud version 30
2. Open a PDF with the Viewer

### Expected behaviour
Tell us what should happen
Normaly it you should see the PDF

### Actual behaviour
Tell us what happens instead, if possible also add a screenshot
When I open the PDF a black screen appears

### Server configuration

**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB

**Nextcloud version:** (see Nextcloud admin page)
30.0.0
<details>
<summary>List of activated apps</summary>
Auditing / Logging
Brute-force settings
External storage support
File sharing
Files download limit
Nextcloud webhook support
Password policy
Share by mail
PDF Viewer 3.0.0	

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Browser

**Browser name:** Firefox/Chrome/Safari/…
In every Browser it doesnt work
**Browser version:** 124/125/…

**Operating system:** Windows/Ubuntu/Mac/…
Windows
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log


```
Browser Console
![image](https://github.com/user-attachments/assets/d312d6dd-4b5a-4d82-beca-bb75b7ab9ed2)

</details>
If I open a PDF normally and i am logged in as a user on the nextcloud, the PDF opens and I see it. But if I share a PDF and open the link in another browser and I'm not logged in there, all I see is a blank screen.

I use docker and there the Nextcloud container:
https://hub.docker.com/layers/library/nextcloud/30.0.0/images/sha256-0f19a49f4169d4622128f73b8b84110dccd8d7b6c925e1cc54860914be549e89?context=explore

Not working:
![nextcloud1](https://github.com/user-attachments/assets/a9a0cb6e-5c56-4df1-849f-822fe851d891)

Working (If iam logged in):
![nextcloud2](https://github.com/user-attachments/assets/9fe60c7e-04c3-4178-82fa-074e179f7537)

**Comment by alpsayin** [comment]
Also affected.

**Comment by boutilpj** [comment]
I tracked down where the 401 is coming from.

apps/dav/appinfo/v2/publicremote.php , starting at line 78.

if ($federatedShareProvider->isOutgoingServer2serverShareEnabled() === false && !$isAjax) {
                // this is what is thrown when trying to access a non-existing share
                throw new NotAuthenticated();
        }


I tested by comment out the throw line and I was able to view the PDF as expected.

Noticing isOutgoingServer2serverShareEnabled , I took a look in Administration settings -> Sharing -> Federate Cloud Sharing and noticed this setting which was off. Turning it on (with the throw back in the above code) also fixes the issue.

 Allow people on this server to send shares to other servers (this option also allows WebDAV access to public shares) .

**Comment by asayin-xlnx** [comment]
Thanks @madrzejewski and indeed Nextcloud update to 30.0.1 fixed it.

**Comment by skjnldsv** [comment]
> Thanks [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/madrzejewski?size=32">@madrzejewski](https://github.com/madrzejewski) and indeed Nextcloud update to 30.0.1 fixed it.

**Comment by fabreupeixoto** [comment]
Greetings to all
Most probably I am not getting many answers as this is already "closed" but I will try anyway as it seems I am still having the same issue, although a bit different, even using version 30.0.2

When a share a pdf file with the "hide download" option the file doesn´t open. It keeps on loading and just don´t open. No matter I am logged in or not. However, the same, which is under a folder, if I share the folder and then opens the files individually it open without any problems.

I notice that on the URL, using this second option, there is kind of an instruction "openfile". I have no idea what it means.

Here is the file that doesn't open: https://bdm-files.usj.edu.mo/index.php/s/rZdKxRRN7m8nk4r

Here is the folder with the file inside and from her it opens without any issues: https://bdm-files.usj.edu.mo/index.php/s/NP6iY4p6z5mtse6

Thank you very much

Best regards,
