### ISSUE TITLE
Nextcloud 29.0.9: `files_pdfviewer-public.js` are missing and PDF documents can't be opened

### ISSUE THREAD

**Issue by mritzmann** [nextcloud/files_pdfviewer#1080]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce

1. Update Nextcloud to version [29.0.9](https://github.com/nextcloud/server/releases/tag/v29.0.9) 
2. Open any PDF

### Expected behaviour

The PDF is displayed in the browser.

### Actual behaviour

The PDF is not displayed in the browser, only offered for download.

### Server configuration

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 8.2.2

**Nextcloud version:** 29.0.9

<details>
<summary>List of activated apps</summary>

```
$ php ~/www/occ app:list
Enabled:
  - activity: 2.21.1
  - cloud_federation_api: 1.12.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - files: 2.1.1
  - files_pdfviewer: 2.10.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - groupfolders: 17.0.5
  - impersonate: 1.16.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - notifications: 2.17.0
  - oauth2: 1.17.1
  - password_policy: 1.19.0
  - previewgenerator: 5.6.0
  - provisioning_api: 1.19.0
  - richdocuments: 8.4.8
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - circles: 29.0.0-dev (installed 0.16.3)
  - comments: 1.19.0 (installed 1.6.0)
  - contactsinteraction: 1.10.0 (installed 1.0.0)
  - dashboard: 7.9.0 (installed 7.0.0)
  - encryption: 2.17.0
  - federation: 1.19.0 (installed 1.6.0)
  - files_downloadlimit: 2.0.0 (installed 2.0.0)
  - files_external: 1.21.0 (installed 1.9.0)
  - files_reminders: 1.2.0 (installed 1.0.0)
  - firstrunwizard: 2.18.0 (installed 2.5.0)
  - nextcloud_announcements: 1.18.0 (installed 1.4.0)
  - photos: 2.5.0 (installed 2.0.1)
  - privacy: 1.13.0 (installed 1.0.0)
  - recommendations: 2.1.0 (installed 0.4.0)
  - related_resources: 1.4.0 (installed 1.1.0-alpha1)
  - support: 1.12.0 (installed 1.0.0)
  - survey_client: 1.17.0 (installed 1.3.0)
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0 (installed 1.6.0)
  - updatenotification: 1.19.1 (installed 1.5.0)
  - user_ldap: 1.20.0
  - user_status: 1.9.0 (installed 1.0.1)
  - weather_status: 1.9.0 (installed 1.0.0)
```
</details>

<details>
<summary>Nextcloud configuration</summary>

I can provide if necessary.

</details>

### Browser

**Browser name:** Firefox

**Browser version:** 132.0.1 (aarch64)

**Operating system:** macOS 14.7

**Comment by mritzmann** [comment]
According to `nextcloud.log` the file `files_pdfviewer-public.js` is missing:

```json
{
    "reqId": "hisLNxFNFjl13wRNglUg",
    "level": 3,
    "time": "2024-11-07T13:59:13+00:00",
    "remoteAddr": "**",
    "user": "--",
    "app": "jsresourceloader",
    "method": "GET",
    "url": "/index.php/s/**",
    "message": "Could not find resource files_pdfviewer/js/files_pdfviewer-public.js to load",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0",
    "version": "29.0.9.2",
    "data": {
        "app": "jsresourceloader"
    }
}
```

And indeed, the file is missing in Nextcloud 29.0.9.

Nextcloud 29.0.8:

```shell
$ wget https://download.nextcloud.com/server/releases/nextcloud-29.0.8.zip
$ unzip -l nextcloud-29.0.8.zip | grep files_pdfviewer-public.js
    79936  2024-10-10 11:13   nextcloud/apps/files_pdfviewer/js/files_pdfviewer-public.js.map
    19184  2024-10-10 11:13   nextcloud/apps/files_pdfviewer/js/files_pdfviewer-public.js
     1683  2024-10-10 11:13   nextcloud/apps/files_pdfviewer/js/files_pdfviewer-public.js.LICENSE.txt
```

Nextcloud 29.0.9:

```shell
$ wget https://download.nextcloud.com/server/releases/nextcloud-29.0.9.zip
$ unzip -l nextcloud-29.0.9.zip | grep files_pdfviewer-public.js
```

**Comment by solracsf** [comment]
Seems to affect **29.0.9 only**.
Both 30.0.2 and 28.0.12 seems OK.

**Comment by szaimen** [comment]
A potential fix is in  https://github.com/nextcloud/files_pdfviewer/pull/1081

**Comment by prghix** [comment]
me affected as well. 29.0.9.

**Comment by solracsf** [comment]
> A potential fix is in [#1081](https://github.com/nextcloud/files_pdfviewer/pull/1081)

Yeah this will fix it. 👍
For those affected, you'll have to wait for v29.0.10.

**Comment by szaimen** [comment]
Fixed via https://github.com/nextcloud/files_pdfviewer/pull/1081

**Comment by Kieltux** [comment]
Local workaround: I copied the files_pdfview directory from 29.0.8 into 29.0.9.

**Comment by Dennis1993** [comment]
I copied the **files** in **apps/files_pdfviewer/js** too and it works now :)

**Comment by Githopp192** [comment]
same: nc 29.0.9, PHP 8.3

> I copied the **files** in **apps/files_pdfviewer/js** too and it works now :)

yes, workaround is working - copied from backup: cp -p ...backup/apps/files_pdfviewer/js/files* ..../apps/files_pdfviewer/js

You need to re-login to make it to work
