### ISSUE TITLE
Allow updating of pdf.js via dependabot

### ISSUE THREAD

**Issue by rullzer** [nextcloud/files_pdfviewer#119]
Installing pdf.js via https://www.npmjs.com/package/pdfjs-dist would make sense I guess. Then we also can keep it automatically up to date.

@juliushaertl @ChristophWurst @danxuliu

**Comment by juliushaertl** [comment]
Yes, we could probably handle this in the same run with https://github.com/nextcloud/server/issues/12382 cc @skjnldsv @jancborchardt

**Comment by skjnldsv** [comment]
Half fixed, we cannot really have dependabot updates.
I spent an entire day trying to use the vuejs-dist library to implement our own pdf front (without iframe). It is a nightmare to do, the whole UI (toolbar, sidebar) is not available on this library, you need to build your own...
![gottimefordat](https://user-images.githubusercontent.com/14975046/90148034-2afe8900-dd83-11ea-8978-c00a9e09eea4.gif)

For now I ended up using an automated way to bundle everything.
https://github.com/nextcloud/files_pdfviewer/blob/c775e153b7fbe765a9d2b405d8716caffc059bc1/webpack.js#L7
