### ISSUE TITLE
Some images in pdf files are not shown using Chromium/Chrome

### ISSUE THREAD

**Issue by dunetna** [nextcloud/files_pdfviewer#120]
### Steps to reproduce
1. Open a PDF with images using Firefox
2. Open a PDF with images using Chromium/Chrome

### Expected behaviour
Images are shown using both browsers.

### Actual behaviour
Images are shown using Firefox, but not using Chrome/Chromium.
But if I use the last version of pdf.js standalone (v2.0.943), PDF images are loaded correctly in both browsers.

### Server configuration
Nextcloud 15.0.2
PDF viewer 1.4.0

### Client configuration
**Browser:** Firefox 60.4.0esr, Chromium 72.0.3626.53
**Operating system:** Debian

**Comment by szaimen** [comment]
Does this still happen with NC21.0.5 or above?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
