### ISSUE TITLE
Search in PDF

### ISSUE THREAD

**Issue by ShinjiLE** [nextcloud/files_pdfviewer#122]
This is more a feature request then a bug report.

### Steps to reproduce
1. open a PDF in NC
2. Press CTRL-F

### Expected behaviour
Search inside the PDF-Viewer should opened.

### Actual behaviour
NC Search is activated . And then it is impossible to close this dialog without leaving the PDF-Viewer because the NC-search will triggered .

**Comment by skjnldsv** [comment]
search works on master
