### ISSUE TITLE
Some PDFs render "bad" (ligatures) with bundled pdf.js 1.9.x -> update to 2.1 ?

### ISSUE THREAD

**Issue by fwolfst** [nextcloud/files_pdfviewer#125]
### Steps to reproduce
1. Open some PDFs that render bad (e.g. incorrect ligature rendering) in pdf.js 1.9.x

### Expected behaviour
Nice ligatures

### Actual behaviour
Bad rendering

### Server configuration
**Nextcloud version:** (see Nextcloud admin page) 15.0.5

**PDF Viewer App Version**: 1.4.0

I stumbled upon a PDF that renders bad in pdf.js 1.9.x (embedded view in nextcloud), but just fine using the latest Firefox (PDF.js: 2.1.220). So I guess this issue relates to https://github.com/nextcloud/files_pdfviewer/issues/119 . I dont know the situation, is there anything speaking **against** updating the bundle `pdf.js`?

I have to check the rights on the document that is "problematic", but I think its rather irrelevant to this issue; its really about updating the plugin / the contained pdf.js.

**Comment by GovetaXV** [comment]
+1

**Comment by skjnldsv** [comment]
Updated
