### ISSUE TITLE
The following list covers which files have failed the integrity check

### ISSUE THREAD

**Issue by Mantinum** [nextcloud/files_pdfviewer#130]
Hello and sorry for my bad english.

Only I encounter a problem with the application:

After updating NC, you can not set the following error message:

The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more
em.

I tried to reinstall the application
To put the right rights
to delete it

But nothing to do always this message:

`Results
=======
- core
	- EXTRA_FILE
		- files_pdfviewer-master/appinfo/info.xml
		- files_pdfviewer-master/appinfo/routes.php
		- files_pdfviewer-master/appinfo/app.php
		- files_pdfviewer-master/.scrutinizer.yml
		- files_pdfviewer-master/vendor/pdfjs/build/pdf.js
		- files_pdfviewer-master/vendor/pdfjs/build/pdf.worker.js.map
		- files_pdfviewer-master/vendor/pdfjs/build/pdf.js.map
		- files_pdfviewer-master/vendor/pdfjs/build/pdf.worker.js
		- files_pdfviewer-master/vendor/pdfjs/web/debugger.js
		- files_pdfviewer-master/vendor/pdfjs/web/viewer.js.map
		- files_pdfviewer-master/vendor/pdfjs/web/locale/pl/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/en-US/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/bn-IN/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/vi/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/da/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/he/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/sw/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/hi-IN/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/tr/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/gu-IN/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/pa-IN/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/gl/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/ms/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/hu/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/kn/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/hr/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/cs/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/ta/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/kk/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/nl/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/ja/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/or/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/lg/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/uk/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/el/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/km/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/ml/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/as/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/cy/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/fy-NL/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/xh/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/gd/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/af/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/fr/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/tn/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/nso/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/is/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/sr/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/bg/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/ak/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/rm/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/fa/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/lt/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/ko/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/locale.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/lij/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/br/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/nb-NO/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/sq/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/ff/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/sv-SE/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/de/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/sah/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/rw/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/es-MX/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/an/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/th/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/sk/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/wo/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/oc/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/ta-LK/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/en-GB/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/pt-BR/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/tl/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/pt-PT/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/bn-BD/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/zu/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/bs/viewer.properties
		- files_pdfviewer-master/vendor/pdfjs/web/locale/mr/viewer.properties
etc...`

thank you very much for your help

**Comment by skjnldsv** [comment]
Cannot reproduce anymore
