### ISSUE TITLE
Server error 500 for PDF shared by link

### ISSUE THREAD

**Issue by GuidoDr** [nextcloud/files_pdfviewer#134]
when a PDF is shared by a link and you click on the link then the PDF viewer does start in the Nextcloud but then does show a server error 500.
![grafik](https://user-images.githubusercontent.com/33029486/57466420-e5e6cf80-7280-11e9-9b0e-c7e6d2ead229.png)

But the PDF Viewer is able to open the file if you nagivate in Nextcloud to the file and click on it.

Nextcloud Version 16.0.0.9 , PDF viewer 1.5.0

{"reqId":"HliaedRcXkNLjEc0t8C1","level":3,"time":"2019-05-09T14:45:26+00:00","remoteAddr":"xx.xx.9.148","user":"--","app":"index","method":"GET","url":"\/s\/rwswf4itSaQdX2X\/download","message":{**"Exception":"InvalidArgumentException"**,"Message":"The given consumer does not implement the \\OCP\\Activity\\IConsumer interface","Code":0,"Trace":[{"file":"\/var\/www\/html\/lib\/private\/Activity\/Manager.php","line":146,"function":"getConsumers","class":"OC\\Activity\\Manager","type":"->","args":[]},{"file":"\/var\/www\/html\/apps\/files_sharing\/lib\/Controller\/ShareController.php","line":686,"function":"publish","class":"OC\\Activity\\Manager","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"\/var\/www\/html\/apps\/files_sharing\/lib\/Controller\/ShareController.php","line":657,"function":"publishActivity","class":"OCA\\Files_Sharing\\Controller\\ShareController","type":"->","args":["public_shared_file_downloaded",["\/Schleswig-Holstein\/Archiv\/Vortr\u00e4ge\/2019-04-08_Fortschritt_im_Recht.pdf"],"user.name",263922,"\/Schleswig-Holstein\/Archiv\/Vortr\u00e4ge\/2019-04-08_Fortschritt_im_Recht.pdf"]},{"file":"\/var\/www\/html\/apps\/files_sharing\/lib\/Controller\/ShareController.php","line":537,"function":"singleFileDownloaded","class":"OCA\\Files_Sharing\\Controller\\ShareController","type":"->","args":[{"__class__":"OC\\Share20\\Share"},{"__class__":"OC\\Files\\Node\\File"}]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"downloadShare","class":"OCA\\Files_Sharing\\Controller\\ShareController","type":"->","args":["rwswf4itSaQdX2X",null,"",""]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareController"},"downloadShare"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareController"},"downloadShare"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareController","downloadShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"token":"rwswf4itSaQdX2X","_route":"files_sharing.sharecontroller.downloadShare"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"token":"rwswf4itSaQdX2X","_route":"files_sharing.sharecontroller.downloadShare"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"token":"rwswf4itSaQdX2X","_route":"files_sharing.sharecontroller.downloadShare"}]},{"file":"\/var\/www\/html\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/s\/rwswf4itSaQdX2X\/download"]},{"file":"\/var\/www\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/lib\/private\/Activity\/Manager.php","Line":96,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"16.0.0.9"}

**Comment by cju77** [comment]
(NC 16.0.1 / PDF-Viewer 1.5.0)

Same issue with guest accounts!

Any hints to fix this?

Thanks!
C.

**Comment by skjnldsv** [comment]
Most likely an old issue with Activity. I cannot reproduce on latest versions of nc.

Please upgrade to a non EOL version (17-18-19 at the time this message is written)
