### ISSUE TITLE
Bad PDF Rendering with UTF-8 / CJK Characters

### ISSUE THREAD

**Issue by zengtianyu1215** [nextcloud/files_pdfviewer#136]
### Steps to reproduce
1. Upload a PDF document which contains the UTF-8 / CJK characters to NextCloud;
2. Open the uploaded document with this PDF viewer;
3. The viewer can just render the western characters but cannot render the characters with the UTF-8 and the CJK encodings.

### Expected behaviour
The UTF-8 characters should be rendered with a readable format.

### Actual behaviour
Cannot display the characters with the UTF-8 / CJK encodings.

### Server configuration

**Operating system**: Linux

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 15.0.8

**Where did you install Nextcloud from:** Official website

**List of activated apps:** Just official apps

**Comment by GovetaXV** [comment]
+1 I think we need to upgrade to pdf.js 2.1

**Comment by juliushaertl** [comment]
Fixed with #140
