### ISSUE TITLE
Printing from IE/ Chrome/Firefox don´t work.

### ISSUE THREAD

**Issue by jdeer333** [nextcloud/files_pdfviewer#150]
Steps to reproduce
1.	Open any PDF file in one of the above mentioned browsers
2.	on upper right click on the Printer symbol
3.	No preview window shows up. No printing dialog shows up

Expected behaviour
It should preview & print (sharp) the whole page

Actual behaviour
The preview and print Dialog do not show up.
I deactivated the pdfviewer app so far for our users have to be able to print pdf files without dowloading and reopening the files circumstantiallyServer configuration.

Operating system: CentOS 7.6.1810 (3.10.0-957.27.2.el7.x86_64)

Web server: apache-4.1.0-5

Database: mysql  Ver 15.1 Distrib 10.3.9-MariaDB

PHP version: PHP 7.2.10

Modules loaded: apcu bz2 calendar Core ctype curl date dom exif fileinfo filter ftp gd gettext hash iconv imagick intl json ldap libxml mbstring mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite Phar posix readline Reflection session shmop SimpleXML sockets SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer wddx xml xmlreader xmlwriter xsl Zend OPcache zip zlib

Nextcloud version:  16.0.4 (stable) 

PDF Viewer Version: 1.5

Updated from: 12.0.3

Where did you install Nextcloud from: NextCloud website

**Comment by szaimen** [comment]
Does this still happen with NC21.0.5 or above?

**Comment by jdeer333** [comment]
No, 
on 21.05 and above it´s working.
Bug can be closed

**Comment by szaimen** [comment]
Thanks for the feedback
