### ISSUE TITLE
Error codes in the log report after opening a pdf-file

### ISSUE THREAD

**Issue by rollanders** [nextcloud/files_pdfviewer#156]
I get an error code after opening a PDF-file. The document opens OK, but I assume that there should not be an error code. 

### Steps to reproduce
1. Open a PDF-file
2. Check in the logg-file (in the UI)

### Expected behaviour
There should be no error report

### Actual behaviour
The file is shown OK but there is an error report. 

## Server configuration detail

**Operating system:** Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64

**Webserver:** nginx/1.15.9 (fpm-fcgi)

**Database:** mysql 10.3.15

**PHP version:** 

7.3.5-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/templates/login.php] => Array
                        (
                            [expected] => 265973da5e4d7d5193f845ce260d5705ef7c0060c00b955b8a37e4858c7519de56cf8ab0ad2bdbb61e75aa15b025d6e3dda1dd4a937ef8569eed92109a9942cc
                            [current] => 74467a4c6261f001afecca93094a61ec70ade758836923578b7ce418423b8986eb47fa54e7ff8439667691ff490f3b9d2fc7abc1608aa1a6629a1bbeb1eb5088
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - apporder: 0.7.1
 - calendar: 1.7.1
 - circles: 0.17.7
 - cloud_federation_api: 0.2.0
 - cms_pico: 0.9.8
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - groupfolders: 4.1.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.1
 - oauth2: 1.4.2
 - onlyoffice: 2.4.0
 - password_policy: 1.6.0
 - provisioning_api: 1.6.0
 - registration: 0.4.7
 - richdocuments: 3.4.1
 - sharebymail: 1.6.0
 - theming: 1.7.0
 - theming_customcss: 1.3.0
 - twofactor_backupcodes: 1.5.0
 - workflowengine: 1.6.0
Disabled:
 - accessibility
 - announcementcenter
 - audioplayer
 - carnet
 - encryption
 - federation
 - files_clipboard
 - files_external
 - files_external_onedrive
 - files_readmemd
 - files_videoplayer
 - firstrunwizard
 - gallery
 - group_everyone
 - nextcloud_announcements
 - notes
 - notifications
 - polls
 - privacy
 - recommendations
 - serverinfo
 - support
 - survey_client
 - suspicious_login
 - systemtags
 - updatenotification
 - user_ldap
 - viewer

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "vmi259531.contaboserver.net",
        "korskyrkan-intra.se"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "overwrite.cli.url": "https:\/\/korskyrkan-intra.se",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "cron_log": true,
    "defaultapp": "apporder",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "filesystem_check_changes": 0,
    "filelocking.enabled": "true",
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "knowledgebaseenabled": false,
    "log_rotate_size": 104857600,
    "logfile": "\/var\/nc_data\/nextcloud.log",
    "logtimezone": "Europe\/Berlin",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "rewrite_url": true,
    "quota_include_external_storage": false,
    "share_folder": "\/Shares",
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto, 7",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "files_clipboard",
        "files_reader"
    ],
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Operating system:** Windows 10 - updated

## Logs

<details><summary>Web server error log</summary>

```
No error in nginx logInsert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
No related error (as I understand) in the nginx/nextcloud.error log. 
```
</details>

<details><summary>Browser log</summary>

[index] Error: TypeError: Argument 5 passed to OC\Core\Controller\PreviewController::__construct() must be of the type string, null given at <<closure>>

 0. <<closure>>
    OC\Core\Controller\PreviewController->__construct("core", OC\AppFramework\Http\Request {}, OC\PreviewManager {}, OC\Files\Node\LazyRoot {}, null, OC\AppFramework\Utility\TimeFactory {})
 1. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 81
    ReflectionClass->newInstanceArgs(["core",OC\AppFr ... }])
 2. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 98
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 3. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OC\\Core\\Controller\\PreviewController")
 4. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 409
    OC\AppFramework\Utility\SimpleContainer->query("OC\\Core\\Controller\\PreviewController")
 5. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 382
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OC\\Core\\Controller\\PreviewController")
 6. /var/www/nextcloud/lib/private/AppFramework/App.php line 113
    OC\AppFramework\DependencyInjection\DIContainer->query("OC\\Core\\Controller\\PreviewController")
 7. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Core\\Controller\\PreviewController", "getPreviewByFileId", OC\AppFramework\ ... {}, {_route: "core.P ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.P ... "})
 9. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "core.P ... "})
10. /var/www/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/core/preview")
11. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

GET /core/preview?fileId=14618&c=30f818f554ac80aa1a8f2702b2e540e4&x=500&y=500&forceIcon=0
from 94.254.30.169 at 2019-09-16T07:33:25+02:00Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by skjnldsv** [comment]
We now display an error
