### ISSUE TITLE
PDFviewer in IE11 does not use full width

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/files_pdfviewer#157]
### Steps to reproduce
1. Open a shared PDF with IE 11

### Expected behaviour
PDF should be viewed in the whole width.

### Actual behaviour
Just 300px are used in the width.
I've posted a workarround (which can be applied permanently) at help.nextcloud.com:
https://help.nextcloud.com/t/link-zu-pdf-dokument-in-ie-wird-nicht-korrekt-angzeigt/38537/5

### Server configuration

**Operating system**: ubuntu server

**Web server:** nginx

**PHP version:** 7.2

**Nextcloud version:** 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** nextcloud.com?

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** IE 11.285.17134.0

**Operating system:** Windows (i hate it!)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/files_pdfviewer/issues/203
