### ISSUE TITLE
Use nextcloud/viewer 

### ISSUE THREAD

**Issue by szaimen** [nextcloud/files_pdfviewer#159]
Please enable us to open pdf files with the viewer app. Would be really awesome beeing able to open pdf files also in other apps like e.g. nextcloud mail for attachments. :)
This is possible since https://github.com/nextcloud/viewer/pull/271

**Comment by juliushaertl** [comment]
I've heard that @danxuliu has been trying to move files_pdfviewer to webpack and update pdfjs so once that has some usabale state it could make use of viewer to integrate in the file list.

**Comment by szaimen** [comment]
@danxuliu is there any update concerning this? :)

**Comment by danxuliu** [comment]
It is high in my TODO, but unfortunately there have been other things with a higher priority on top ;-) But hopefully I will find some time to work on it _soon™_

**Comment by skjnldsv** [comment]
Done

**Comment by szaimen** [comment]
Wow that was fast 🎉

**Comment by skjnldsv** [comment]
I broke my brain for two days trying to implement everything without an iframe and proper library, it's not feasible.
Now it's at least super clean and faster :)

**Comment by onny** [comment]
Wow that sounds impressive, could you share an screenshot? :O :D

**Comment by skjnldsv** [comment]
I'm out for the day :)
It will be part of nc20 
It's basically just integrated into the Viewer that displays all the images, videos... Etc 🥳

**Comment by onny** [comment]
With a few css styling fixes one could get rid of the dysfunctional close button and the background pattern in pdfjs :+1: 

![20201010_10h05m01s_grim](https://user-images.githubusercontent.com/757752/95649945-0ba88180-0ad0-11eb-9d9c-e2836c0e3c83.png)
