### ISSUE TITLE
Please make files_pdfviewer the default app for opening illustrator files (.ai)

### ISSUE THREAD

**Issue by szaimen** [nextcloud/files_pdfviewer#162]
In my experience, many Illustrator files (.ai) can get opened with a pdf reader because they are compatible. So why not making this app to the default also for opening .ai files?
(to my knowledge Illustrator files otherwise cannot get opened or shown in the Nextcloud universe today)
(the best proof was, that I renamed a .ai file to a .pdf file and opened it with the pdfviewer -> it worked.)

**Comment by szaimen** [comment]
@skjnldsv if I remember correctly there must be a place where you can define supported mimetypes.
Would .ai support for the files_pdfviewer now be easy to implement? (I imagine that you just add the mimetype to by the pdfviewer supported mimetypes...

**Comment by skjnldsv** [comment]
Hey! Why not!
Check the main.js file in the src folder :)

**Comment by szaimen** [comment]
Cool!
Since based on [this source](https://webstoked.com/mime-type-adobe-illustrator-ai-files/) do .ai files also have the same mime-type `application/pdf`, is it enough to add ai as an additional id here:
https://github.com/nextcloud/files_pdfviewer/blob/0c309be23904a8ab823700754c6a1c02fb4a745d/src/main.js#L27

So I would change this line to something like `id: 'pdf', 'ai',` 
Would that work?

**Comment by skjnldsv** [comment]
> Since based on [this source](https://webstoked.com/mime-type-adobe-illustrator-ai-files/) do .ai files also have the same mime-type `application/pdf`.

No, the id is a unique identifier for this viewer view provider :)
If this is not working out of the box, it means Nextcloud is seeing the file as a different mime
![image](https://user-images.githubusercontent.com/14975046/90169782-5d1de400-dd9f-11ea-8506-a615e7eb131c.png)

Please use `application/illustrator`

**Comment by szaimen** [comment]
Okay great! Thanks for your guidance! :) 
It should be really easy then to implement.

I opened #196 for that.
