### ISSUE TITLE
Incomplete display of PDF files

### ISSUE THREAD

**Issue by Bables55** [nextcloud/files_pdfviewer#167]
### Steps to reproduce
1. Attempt to preview a PDF that contains selectable text.
2. The PDF itself opens.

### Expected behaviour
Open without problems.

### Actual behaviour
- Double-byte fonts are not displayed completely.
- Other background vector elements (such as squares and lines) are displayed in an incomplete state. Elements that should be displayed in gradation colors are single color display.

### Server configuration

**Operating system**:
CentOS 7.7
**Web server:**
nginx 1.16.1
**Database:**
MariaDB 10.2.31
**PHP version:**
PHP 7.3.15
**Nextcloud version:** (see Nextcloud admin page)
NC 18.0.2
**PDF Viewer**
1.7.0

### Client configuration
**Browser:**
Firefox, Chrome, Vivaldi, Edge(new)
Internet Explorer was able to display without problems.

**Operating system:**
Windows10

#### Browser log
```
await fetch("https://MY-NEXTCLOUD/apps/files_pdfviewer/vendor/pdfjs/build/pdf.js?v=1.7.0", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
        "Accept": "*/*",
        "Accept-Language": "ja,en-US;q=0.7,en;q=0.3"
    },
    "method": "GET",
    "mode": "cors"
});

await fetch("https://MY-NEXTCLOUD/apps/files_pdfviewer/vendor/pdfjs/web/viewer.js?v=1.7.0", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
        "Accept": "*/*",
        "Accept-Language": "ja,en-US;q=0.7,en;q=0.3"
    },
    "method": "GET",
    "mode": "cors"
});

await fetch("https://MY-NEXTCLOUD/apps/files_pdfviewer/js/workersrc.js?v=1.7.0", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
        "Accept": "*/*",
        "Accept-Language": "ja,en-US;q=0.7,en;q=0.3"
    },
    "method": "GET",
    "mode": "cors"
});
```
pdf.js viewer.js workesrc.js is blocked. 
I suspected CORS and added a header to nginx, but nothing changed.
Nextcloud and PDF files are of course on the same server.

**Comment by y377** [comment]
```
PHP

7.4.24

Memory Limit: 512 MB

Max Execution Time: 3600

Upload max size: 800 MB
Database

mysql

10.3.28

3.2 MB
```
me too

**Comment by skjnldsv** [comment]
Hi, is this issue still happening ?
