### ISSUE TITLE
Can find pdf.worker.js

### ISSUE THREAD

**Issue by admorgan** [nextcloud/files_pdfviewer#172]
### Steps to reproduce
Open a PDF in the file viewer

### Expected behaviour
PDF viewer opens and displays PDF

### Actual behaviour
PDF Viewer opens, displays error about finding pdf.worker.js

## Server configuration detail

**Operating system:** Linux 4.12.5-gentoo #1 SMP Fri Aug 25 00:20:17 CDT 2017 i686

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** pgsql PostgreSQL 11.4 on i686-pc-linux-gnu, compiled by i686-pc-linux-gnu-gcc (Gentoo 7.3.0-r3 p1.4) 7.3.0, 32-bit

**PHP version:** 

7.3.16
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dba, dom, hash, fileinfo, filter, gd, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, mysqli, PDO, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, Reflection, imap, SimpleXML, exif, tokenizer, xml, xmlreader, xmlwriter, zip, cgi-fcgi, imagick, redis, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 18.0.2

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - deck: 0.8.0
 - drawio: 0.9.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_mindmap: 0.0.20
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.1
 - groupfolders: 6.0.3
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.4
 - maps: 0.1.6
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - passwords: 2020.3.1
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - documentserver_community
 - encryption
 - files_external
 - onlyoffice
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.morgancomputers.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/nextcloud.morgancomputers.net",
    "dbtype": "pgsql",
    "version": "18.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "updater.release.channel": "stable",
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "calendar",
        "drawio",
        "files_mindmap"
    ],
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***",
        "dbindex": 0
    },
    "defaultapp": "apporder"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Vivaldi

**Operating system:** OpenSUSE Tumbleweed

## Logs

<details><summary>Web server error log</summary>

```
Nothing in log
```
</details>

<details><summary>Nextcloud log</summary>

```
Nothing in log
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

The javascript console log:
Uncaught ReferenceError: PDFJS is not defined
    at HTMLDocument.initializeCustomPDFViewerApplication (workersrc.js?v=1.7.0:31)

</details>

**Comment by skjnldsv** [comment]
Fixed
