### ISSUE TITLE
"Hide Download" URL sharing does not display the shared PDF file.

### ISSUE THREAD

**Issue by kshimohata** [nextcloud/files_pdfviewer#174]
### Steps to reproduce
1. Enable "Hide Download" for URL sharing of the PDF file.
2. Access the URL in 1. in my browser.

### Expected behaviour
The contents of the PDF file will be displayed.

### Actual behaviour
The contents of the PDF file are not displayed and "Missing PDF file." is displayed.

### Additional Information
* If "Hide Download" is disabled, the contents of the PDF file will be displayed.
* In "Nextcloud 18.0.3",
    * The contents of the PDF file will be displayed when the URL is shared with "Hide Download" enabled.
    * If I enable "Hide Download" and share the folder URL and access the PDF file in it, I will see "Missing PDF file.
* In "Nextcloud 16.0.5",
    * The contents of the PDF file will be displayed when the URL is shared with "Hide Download" enabled.
    * If I enable "Hide Download" and share the folder URL and access the PDF file in it, I will see the contents of the PDF file.

### Server configuration detail

**Operating system:** Linux 4.15.0-1052-aws #54-Ubuntu SMP Tue Oct 1 15:43:26 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.29

**PHP version:** 7.3.16

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gmp, SPL, iconv, intl, json, ldap, mbstring, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 17.0.5 - 17.0.5.0

**Where did you install Nextcloud from:** Snap package install

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/server/pull/20131
