### ISSUE TITLE
Opening Links in PDF

### ISSUE THREAD

**Issue by remmedia** [nextcloud/files_pdfviewer#175]
Changed comment to make it more clear and reproducebale

Attach (recommended) or Link to PDF file here:
[https.pdf](https://github.com/mozilla/pdf.js/files/4533040/https.pdf)

### Steps to reproduce the problem:
1. open attached file with pdf.js (inside nextcloud)
2. click the links

### What is the expected behavior? (add screenshot)
for the three links
a) a pdf file is shown
b) form is working
c) on click on "Download Sample PDF File" this file is shown

### What went wrong? (add screenshot)
for the three links
a) page keeps blank
b) form is not working
c) page works but on click on "Download Sample PDF File" target keeps blank

**Reproducable**
to reproduce the problem you can use the public demo of nextcloud:
https://try.nextcloud.com and upload the attached file.

**Hint**
If you right-click the links and select "open in new window" or "open in new tab" or open the pdf file with any other pdf viewer, everything works fine.

### Server configuration
**Operating system:**
Debian
**Web server:**
Apache 2.4
**Database:**
mysql
**PHP version:**
php 7.4.4
**Nextcloud version:** (see Nextcloud admin page)
18.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
update

### Client configuration
**Browser:**
different one
using chrome 81.0.4044.122 (Offizieller Build) (64-Bit)
**Operating system:**
different
using Windows 10 Pro 10.0.18363
**PDF.js version:**
1.7 and 2.3.200 (changed version to make sure it is not because old version of pdf.js)

**Comment by remmedia** [comment]
Ok, got it mysqlf inside js/previewplugin.js there the iframe uses `sandbox` parameter, which will make this error occour.
any idea how to fix it?

by the way it would be nice to see if pdf.js would be updated to 2.3

**Comment by skjnldsv** [comment]
Fixed with nc 20
