### ISSUE TITLE
sidebar remains open and doesn't update

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/files_pdfviewer#183]
### Steps to reproduce
1. open the sidebar on some other file
2. click on a PDF file in the same folder
3. PDF viewer opens

### Expected behaviour
Either sidebar remains open but shows the opened PDF's details or sidebar closes. The latter would be prefered but not before https://github.com/nextcloud/files_pdfviewer/issues/118 is possible.

### Actual behaviour
Sidebar remains open, displaying the details of the previously viewed file.

![issueSidebar](https://user-images.githubusercontent.com/1804221/82286846-ff941a00-999e-11ea-9247-745bef663467.gif)

### Server configuration
Tested with Chrome 81 and Firefox 76 on 
- NC 18.0.4 + files_pdfviewer 1.7.0
- NC 19.0.0 RC2  + files_pdfviewer 1.8.0

**Comment by szaimen** [comment]
I guess this is a duplicate of #191
