### ISSUE TITLE
Locale properties don't load when friendly urls is enabled

### ISSUE THREAD

**Issue by lainosantos** [nextcloud/files_pdfviewer#190]
### Steps to reproduce
1. Active friendly urls
2. Click in file to preview

### Expected behaviour
Load locale translations according the browser locale

### Actual behaviour
*.properties files is not loaded because rewrite rules in .htaccess change the request to index.php

Add an entry in .htacess to allow pdfjs vendor files solves the problem

```
...
RewriteCond %{REQUEST_URI} !^/apps/files_pdfviewer/vendor/pdfjs/.*
RewriteRule . index.php [PT,E=PATH_INFO:$1]
```

**Comment by skjnldsv** [comment]
Should be fixed :)

**Comment by lainosantos** [comment]
This bug remain present in nc20.
