### ISSUE TITLE
Close icon in PDF viewer

### ISSUE THREAD

**Issue by mammutserver** [nextcloud/files_pdfviewer#198]
The close icon on the PDF viewer has a weird behavior in my browser(s). I tested it with Chrome,Firefox, Opera and Safari on several devices.

Server version: 19.0.1
PHP version: 7.4.7
Webserver: NGINX

Further information can be provided on request.

![image](https://user-images.githubusercontent.com/46828369/89506645-b8fad280-d7cb-11ea-9a83-f972d0f54531.png)

**Comment by skjnldsv** [comment]
Can someone try with master and nc20? :)

**Comment by skjnldsv** [comment]
FIxed
