### ISSUE TITLE
adress pdf parameter

### ISSUE THREAD

**Issue by hirschrobert** [nextcloud/files_pdfviewer#20]
IT would be great to be able to adress [pdf parameters](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf) also for pdf documents in the cloud.

Click on http://example.org/index.php/apps/files_pdfviewer?file=%2Fremote.php%2Fwebdav%2Fexample.pdf#page=10 should lead directly to pdf bookmark on page 10 while logged in.

For external pages it works.

Thanks!

**Comment by hirschrobert** [comment]
Hey @MorrisJobke , thanks for the great conference. Here my idea to extend the pdf viewer so that pdf parameters can be addressed directly. Maybe its possible to simply extend the [showPdfViewer](https://github.com/nextcloud/files_pdfviewer/blob/e7ff2bf1c557ab0a7a50bf227d8c50742958637a/controller/displaycontroller.php#L43-L58) function, at leas as a first step? Ideally for the enduser you should write something like nc.example.org/index.php/f/12345#page=12 and reference pdf content directly (i.e. in mails and link directly to the content if logged in in nc). what do you think? Thanks!

**Comment by MorrisJobke** [comment]
Maybe somebody from the @nextcloud/javascript group wants to pick this up.

**Comment by hirschrobert** [comment]
I fiddled around a bit. 
Lesson No 1: anchors (#page=12) are client business, so params array via php won't work.

Secondly, because the use of anchors only makes sense when using the fileid link, I ended up in the viewcontroller of the files app. Maybe [here](https://github.com/nextcloud/server/blob/master/apps/files/lib/Controller/ViewController.php#L258-L264) to use a Templateresponse in case of a pdf file with $renderAs='user'. Would that work? We could extend that further to any app out there depending on the mime type.

Then the anchor "#page={page}" would need to be preserved and passed on via javascript. Where could I do that?

**Comment by mahbgithub** [comment]
Hi,
I'm also highly interested in finding a solution to link to a certain page in a PDF. I already made a post in the NextCloud forum: https://help.nextcloud.com/t/link-to-pdf-page-2/23817/2
Anyhow there was no reply on it.
I checked it with a Microsoft sharepoint, and there it is working. Anyhow they generate different links:
https://xxxx.sharepoint.com/personal/pdffile.pdf?slrid=5d2f2f9f-3389-0004-98fc-e86ad4be8c52
if you then add a #page=2 you directly jump to page 2.
I'm fare of being a computer expert but I would think this should be possible here as well...
But I can't find a way.
I currently prepare a report from which I'm linking to several other reports. And it would be more than handy to not only link to the PDF but directly to the Page where the reference is shown.
Help & Assistance is highly appreciated.
Best regards
Martin

**Comment by NeoJones** [comment]
Hi,
iam also very interesting to find a solution about this feature. At this moment I dont see a way, too...
Help please...

Best regards
Olli

**Comment by NeoJones** [comment]
Okay, so I think I have a solution. I think, its not the best code cause iam a javascript beginner.
With the following changes you can use urls for example:

`https://myAdress/index.php/s/awV0eWrbqtGR7tv#pdfviewer?page=2`

Replace in **/apps/files_pdfviewer/js/previewplugin.js** on line 92:

```
if(!$('html').hasClass('ie8')) {
	history.pushState({}, '', '#'+url_end);
}
```
to
```
if(!$('html').hasClass('ie8')) {
	var url_string = window.location.href;
	var url_arr = url_string.split("#");
	var url_end = url_arr[1];		
	history.pushState({}, '', '#'+url_end);
}
```
Replace in **/apps/files_pdfviewer/vendor/pdfjs/web/viewer.js** on line 7415:
```
document.addEventListener('pagerendered', function (e) {
  var pageNumber = e.detail.pageNumber;
  var pageIndex = pageNumber - 1;
  var pageView = PDFViewerApplication.pdfViewer.getPageView(pageIndex);

  if (PDFViewerApplication.sidebarOpen) {
    var thumbnailView = PDFViewerApplication.pdfThumbnailViewer.
                        getThumbnail(pageIndex);
    thumbnailView.setImage(pageView);
  }

  if (PDFJS.pdfBug && Stats.enabled && pageView.stats) {
    Stats.add(pageNumber, pageView.stats);
  }

  if (pageView.error) {
    PDFViewerApplication.error(mozL10n.get('rendering_error', null,
      'An error occurred while rendering the page.'), pageView.error);
  }

  // If the page is still visible when it has finished rendering,
  // ensure that the page number input loading indicator is hidden.
  if (pageNumber === PDFViewerApplication.page) {
    var pageNumberInput = document.getElementById('pageNumber');
    pageNumberInput.classList.remove(PAGE_NUMBER_LOADING_INDICATOR);
  }
}, true);
```
to
```
var isfirstload = 0;
document.addEventListener('pagerendered', function (e) {
  var pageNumber = e.detail.pageNumber;
  var pageIndex = pageNumber - 1;
  var pageView = PDFViewerApplication.pdfViewer.getPageView(pageIndex);

  if (PDFViewerApplication.sidebarOpen) {
    var thumbnailView = PDFViewerApplication.pdfThumbnailViewer.
                        getThumbnail(pageIndex);
    thumbnailView.setImage(pageView);
  }

  if (PDFJS.pdfBug && Stats.enabled && pageView.stats) {
    Stats.add(pageNumber, pageView.stats);
  }

  if (pageView.error) {
    PDFViewerApplication.error(mozL10n.get('rendering_error', null,
      'An error occurred while rendering the page.'), pageView.error);
  }

  // If the page is still visible when it has finished rendering,
  // ensure that the page number input loading indicator is hidden.
  if (pageNumber === PDFViewerApplication.page) {
    var pageNumberInput = document.getElementById('pageNumber');
    pageNumberInput.classList.remove(PAGE_NUMBER_LOADING_INDICATOR);
  }
	if(isfirstload == 0){
		var url_str = window.parent.location.href;
		var url_arr = url_str.split("#");
		var url_end = url_arr[1];
		var search_page = url_end.replace('pdfviewer?page=', '');
		document.getElementById('pageNumber').value = search_page;
		PDFViewerApplication.page = search_page;
		isfirstload = 1;
	}
}, true);
```

I hope it helps ;-)

Regards, Olli

**Comment by MorrisJobke** [comment]
@NeoJones Mind to hand in the change as pull request? Then we can put comments on the code and actually test this. Also the IE8 support can be dropped completely ;) We support IE11 and up ;)

**Comment by hirschrobert** [comment]
thanks @NeoJones . I created [a pull request](https://github.com/nextcloud/files_pdfviewer/pull/58), with a different approach.

**Comment by skjnldsv** [comment]
Fixed nc 20
