### ISSUE TITLE
PDF viewer 1.8.0 shows only parts of images

### ISSUE THREAD

**Issue by erikfdev** [nextcloud/files_pdfviewer#227]
### Steps to reproduce
1. open the attached file in nextcloud PDF viewer
[ZONDAGSVIERINGEN 24e zondag A website 2020-boekje.pdf](https://github.com/nextcloud/files_pdfviewer/files/5199970/ZONDAGSVIERINGEN.24e.zondag.A.website.2020-boekje.pdf)

2.notice the partially displayed images

### Server configuration

Nextcloud 19.0.2 (and earlier)
**Operating system**:
 Linux Mint 19.3 Tricia
**Web server:**
Apache 2.4.29
**Database:**
Sqlite
**PHP version:**
PHP 7.2.24
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 19.0.2
**Where did you install Nextcloud from:**

### Client configuration
**Browser:**
Firefox 80.0.1
**Operating system:**
Windows 10

### Probable cause
The probable cause is the out of date pdf.js version (2.1.266). This issue is fixed in more recent pdf.js versions such as 2.4.456.
### Request
Since nextcloud release 19 is now the ' stable'  release, please update files_pdfviewer for nextcloud 19 with a more up to date pdf.js from Mozilla.

**Comment by skjnldsv** [comment]
Then fixed with nc20 :)

**Comment by erikfdev** [comment]
Why not backport to nextcloud 19? Nextcloud 20 is still beta.

**Comment by skjnldsv** [comment]
Because it's too much of a change this time :)
You'll have to wait a bit :wink:

**Comment by erikfdev** [comment]
OK..
In the meanwhile I fixed it myself on my server, by replacing the vendor/pdfjs directory by the one of Mozilla pdf.js 2.4.456.

I had to clear the cache of my browser, tough, to force the use of the updated pdf.js.
