### ISSUE TITLE
Embed pdf on other site

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/files_pdfviewer#229]
### Steps to reproduce
1. Try to embed a pdf from Nextcloud
2. https://codimd.indie.host/C8sDlTXsRtaSpRbj0BHYtg#

### Expected behaviour

It should embed it.

### Actual behaviour

It doesn't.

I guess this relates to this issue:
https://github.com/nextcloud/server/pull/6599

Do you think it is better to open it here, or on the server?

Thanks for your help :)

**Comment by skjnldsv** [comment]
I'm not sure about how to embed, but using the direct download link from  https://github.com/nextcloud/server/pull/6599 should work yeah
