### ISSUE TITLE
Add PDF viewer function to an another Nextcloud App

### ISSUE THREAD

**Issue by garybsimon** [nextcloud/files_pdfviewer#23]
Hi,

I want to add the PDF viewer function to another Nextcloud App like Mail and Rainloop.
The key problem is that, there is no working PDF preview after some update.

How can I assign this PDF viewer to the Mail app? 

Can someone help me out?

Thanks.

**Comment by skjnldsv** [comment]
Fixed on master with the use of https://github.com/nextcloud/viewer
