### ISSUE TITLE
Files shared via link do not honour the "hide download" setting

### ISSUE THREAD

**Issue by mikebakke** [nextcloud/files_pdfviewer#246]
### Steps to reproduce
1. add a pdf to files
2. create a link and select "hide download" checkbox
3. access link via browser

### Expected behaviour
The pdf should be displayed without the button to download

### Actual behaviour
The pdf is displayed but also has the download button enabled

### Server configuration
Rpi 4 / 4G memory
**Operating system**:
Raspbian 64

**Web server:**
NGINX

**Database:**
MySQL

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
20.0.0

**Where did you install Nextcloud from:**
tarball from nextcloud.com

**List of activated apps:**
PDF viewer 2.0.1

================================================
On the same infrastructure, I have another Nextcloud instance running at 18.05 - performing the same test returns the expected behaviour from pdf viewer 1.7.0

Text, img and video files when viewed via link on 20.0.0 behave correctly - the download option is not displayed

**Comment by mikebakke** [comment]
Good afternoon

I just upgraded to 20.01 and tested the new app version. Unfortunately, the user is still able to download the PDF by clicking a button. There is a difference when the hide download box is checked. 

Attached are two screenshots taken after the same link to a PDF is opened
1. Without hide selected - there is a large download button above the document
2. Hide has been selected - there is a smaller download icon in the header of the displayed document
Clicking on either button will download the file

Please ask if you need any further info

Many thanks

Mike
![image](https://user-images.githubusercontent.com/55141164/97183083-3c0d4280-1795-11eb-8e28-273920803809.png)
![image](https://user-images.githubusercontent.com/55141164/97183135-4deee580-1795-11eb-8a71-8f4b82d029f0.png)

**Comment by skjnldsv** [comment]
Fixed already in https://github.com/nextcloud/files_pdfviewer/pull/247
20.0.1

**Comment by mikebakke** [comment]
Hi again

The screenshots above were taken from my upgraded system - Nextcloud version 20.0.1 and PDF viewer 2.0.1

![image](https://user-images.githubusercontent.com/55141164/97186809-a88a4080-1799-11eb-816f-e1df23f1caea.png)

**Comment by skjnldsv** [comment]
Ah, thanks!
https://github.com/nextcloud/files_pdfviewer/pull/247 fixed half of the issue, see https://github.com/nextcloud/files_pdfviewer/pull/256

**Comment by mikebakke** [comment]
No problem - many thanks :-)
