### ISSUE TITLE
All layers printed, disregarding saved choices

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [nextcloud/files_pdfviewer#255]
### Steps to reproduce
1. Open https://cloud.enabled.page/s/5xztQLCSEwLWzyP
2. Note left side of first page is illegible. If you download and open, you'll find that the dice do not show up, and there's only one instance of the names instead of overlapping

### Expected behaviour
Tell us what should happen

Either there should be an option similar to thumbnail to allow enabling/disabling layers, or it should honor the saved predefinition of which layers should show.

### Actual behaviour
Tell us what happens instead

All layers are rendered and no control exists to restrict.

### Server configuration

**Operating system**: Debian 10

**Web server:** docker nginx-proxy/cron/redis/fpm

**Database:** MariaDB 10.4.11

**PHP version:** 7.4.10

**Nextcloud version:** (see Nextcloud admin page) 19.3

**Where did you install Nextcloud from:** docker official nextcloud

**List of activated apps:** 

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.1.2
  - documentserver_community: 0.1.8
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_photospheres: 1.19.1
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.1.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - news: 14.2.2
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.1.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.5
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - calendar
  - contacts
  - encryption
  - epubreader
  - files_external_dropbox
  - keeweb
  - mail
  - ocr
  - richdocuments
  - richdocumentscode
  - spreed
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.enabled.page"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "http:\/\/cloud.enabled.page",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:** Firefox 81.0.1 (64-bit)

**Operating system:** Tumbleweed/Linux Mint 20.0

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by skjnldsv** [comment]
This is part of upcoming pdf.js version https://github.com/mozilla/pdf.js/releases/tag/v2.6.347
We can't do anything until it is released.
It will have to wait :)

**Comment by all-the-good-ones-are-gone** [comment]
Well, that's nice to hear.

Would you estimate that it'd be weeks or months to make its way to us?

**Comment by skjnldsv** [comment]
I cannot, this library is managed by Mozilla and we have no control over when it will be released :(
As soon as we'll be able to, we'll do the upgrade :)
