### ISSUE TITLE
PDFviewer not starting. Shows blank page

### ISSUE THREAD

**Issue by joekerna** [nextcloud/files_pdfviewer#26]
Nextcloud 11.0.2 (beta)
PHP: 7.0.15
Nginx, Ubuntu

I can't open PDFs in PDFviewer on my own Nextcloud instance. Nextcloud just opens a blank white page and does not seem to even load the PDF plugin.

Firefox Console gives me a JS Warning

> Load denied by X-Frame-Options ..... files_pdfviewer .... does not permit framing

On demo.nextcloud.com however I can open PDFs just fine. So it seems to be an issue with my setup.
Are there any specific Nginx options I have to set/unset?

I don't know if this is related but Collabora-Office documents behave exactly the same. Not opening Collabora, only blank white page.

**Comment by joekerna** [comment]
I've been able to fix the problem.
My Nginx setup contained two X-Frame-Options statements that were overwriting each other. In the end X-Frame-Options were set to _deny_ which caused the PDFviewer not to show up.

**Comment by scurrvy2020** [comment]
This helped me out. removed the security flags and fixed my pdf viewer!  thanks!
