### ISSUE TITLE
Very strange empty space at the bottom of the page in 20.0.2

### ISSUE THREAD

**Issue by elpraga** [nextcloud/files_pdfviewer#268]
In NC 20.0.2 PDFviewer leaves a very bug-like looking space under the displayed PDF.

![image](https://user-images.githubusercontent.com/13814570/99914657-2b51dd00-2cff-11eb-8495-8ac5837fdf6a.png)

**Comment by elpraga** [comment]
Notice the part with **Settings** - it clearly should not be visible. Still those huge bezels :(

**Comment by skjnldsv** [comment]
Please use the issue template
