### ISSUE TITLE
How to set default values for Zoom and ScrollMode

### ISSUE THREAD

**Issue by nousernameavailableanymore** [nextcloud/files_pdfviewer#280]
I tried setting default values for `defaultZoomValue` and `pdfjs.scrollModeOnLoad` in `/var/www/nextcloud/apps/files_pdfviewer/vendor/pdfjs/web/viewer.js`.

However, that did not change the default value for new pdfs.

What are the intended steps to configure the default values for Zoom and ScrollMode?
NC version: 19.0.6
app version: 1.8.0

Thank you.

**Comment by skjnldsv** [comment]
Hi, sorry, this is not supported.
We can't provide support for custom configs/change of the nextcloud code.

Also, since 20, this app changed entirely and the old legacy code is not used anymore

Thanks for your understanding
Have a great day and happy new year! :)
