### ISSUE TITLE
Can't open PDF file in viewer when filename is containing a plus (+) sign in shared folder

### ISSUE THREAD

**Issue by m1d1** [nextcloud/files_pdfviewer#285]
### Steps to reproduce
1.  Share a folder
2. Add a PDF file to to the folder. PDF filename containing a (plus) "+" sign. (e.g. name it `one + one.pdf`) 
3. Open shared folder link (inkognito mode). Open PDF file "one + one.pdf"

### Expected behaviour
Open the PDF with PDF viewer

### Actual behaviour
PDF viewer opens with error message: File is missing 
```
PDF.js Version 2.4.456 (build: 228a591c)
Nachricht: Missing PDF "https://somedomain.net/index.php/s/someid/download?path=/&files=one+one.pdf".
```

**Operating system**:

**Web server:**
apache 2.4.6

**Database:**
mariadb 5.5.68

**PHP version:**
php 7.3.25

**Nextcloud version:** (see Nextcloud admin page)
20.0.4

**Where did you install Nextcloud from:**
I didn't. Running instance since nextcloud v11. 

**List of activated apps:**
Default stock apps, only. List of disabled Apps: dashboard, encryption, files_external, files_version, user_status, weather_status.

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Cent OS 7.9.2009
#### Nextcloud log (data/owncloud.log)
```
PDF.js Version 2.4.456 (build: 228a591c)
Nachricht: Missing PDF "https://somedomain.net/index.php/s/someid/download?path=/&files=one+one.pdf".
```

**Comment by samweisgamdschie** [comment]
It seems to be fixed in 20.0.8, see https://github.com/nextcloud/files_pdfviewer/pull/321
