### ISSUE TITLE
printing from IE / Edge produces only half of page, from Chrome it's blurry

### ISSUE THREAD

**Issue by hillebr** [nextcloud/files_pdfviewer#30]
### Steps to reproduce
1. Open any PDF file in one of the above mentioned browsers
2. on upper right click on the Printer symbol
3. in the preview window you can see in IE / Edge only the half of the page an printing out will be the same (Chrome prints the whole page but quite blurry)

### Expected behaviour
It should preview & print (sharp) the whole page

### Actual behaviour
It only prints half of the page in IE / Edge, in Chrome it prints the full page but blurry
I deactivated the pdfviewer app so far for our users have to be able to print pdf files without dowloading and reopening the files circumstantially

### Server configuration
**Operating system**: Linux etinc002 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 10.0.30

**PHP version:** 7.0.19-1~dotdeb+8.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, igbinary, msgpack, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, mcrypt, memcached, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, pspell, readline, recode, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from:** 11.0.1

**Where did you install Nextcloud from: NextCloud website** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - admin_audit: 1.1.0
 - comments: 1.1.0
 - dav: 1.1.1
 - encryption: 1.4.1
 - external: 1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_accesscontrol: 1.1.2
 - files_external: 1.1.2
 - files_retention: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - user_external: 0.4
 - user_ldap: 1.1.2
 - user_saml: 1.2.2
 - workflowengine: 1.1.1

Disabled:
 - files_automatedtagging
 - files_pdfviewer
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocx4azaipitv",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "10.192.1.24",
        "cloud.entireinfra.com"
    ],
    "datadirectory": "\/var\/www\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/10.192.8.80\/nextcloud",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "CET",
    "loglevel": "3",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "log_rotate_size": 133120,
    "installed": true,
    "updater.release.channel": "stable",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "auth.bruteforce.protection.enabled": false,
    "mail_smtpmode": "smtp",
    "mail_from_address": "Cloud",
    "mail_domain": "e-infra.com",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "10.192.8.12",
    "mail_smtpport": "25252",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

### Client configuration
**Browser: Microsoft EDGE**

**Operating system: Windows 10 Pro 1703**

**Comment by JK74** [comment]
Is there any update or planned fix for this issue?

**Comment by spralexx** [comment]
Same problem here.
