### ISSUE TITLE
Get: Fehler "cURL error 3: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)" opening all PDF-Files

### ISSUE THREAD

**Issue by Hagebutt3** [nextcloud/files_pdfviewer#310]
What might be wrong?

**Operating system**: w10

**Web server:**Linux 5.4.89 x86_64

**Database:**

**PHP version:**7.4

**Nextcloud version:** (see Nextcloud admin page)20.0.8
**Browser** FF 85.0.2

I tried deactivate "PDF-Viewer", too, but still same behavior
Thanks a lot!
MAtthias

**Comment by skjnldsv** [comment]
Fixed on latest, wait for upcoming update
