### ISSUE TITLE
PDF Viewer opens but no content is displayed if filename or foldername contain a blank ( ) or (#) or (+)

### ISSUE THREAD

**Issue by christophstephan** [nextcloud/files_pdfviewer#334]
### Steps to reproduce
1.open cloud
2.click on pdf-file
3.

### Expected behaviour
pdf-viewer should open and display the pdf-file

### Actual behaviour
pdf-viewer opens but nothing else happens. As soon as the blank or # or + are deleted from the filename or foldername, 
pdf viewer displays the content of the pdf-file as expected.

### Server configuration

**Operating system**:Linux 5.4.0-66-generic x86_64

**Web server:**nginx/1.18.0

**Database:**mysql Version: 8.0.23

**PHP version:**7.4.15

**Nextcloud version:** (see Nextcloud admin page) 21.0.0

**Where did you install Nextcloud from:**Website

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:** Edge chromium Version 89.0.774.45 (Offizielles Build) (64-Bit)

**Operating system:**Windows 10 Pro Version 20H2 Build 19042.804

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by skjnldsv** [comment]
Hey, see https://github.com/nextcloud/viewer/issues/415 :)
Thanks!
