### ISSUE TITLE
Not merged in 20.0.8 compressed file

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/files_pdfviewer#344]
Hi on your repository you said
Fix opening pdf files in public folder shares (files_pdfviewer#321) (https://nextcloud.com/changelog/#latest20) 
The content are not the same in 
https://github.com/nextcloud/files_pdfviewer/tree/stable20
and your 
compressed file 

I saw that when i updated nextcloud 20.0.7 to nextcloud 20.0.8 to correct this issue https://github.com/nextcloud/files_pdfviewer/pull/321

but nothing append until i remove the files_pdfviewer and clone it from your repository
git clone https://github.com/nextcloud/files_pdfviewer.git --branch stable20

I think files_pdfviewer is not correctly updated inside your compressed file

Best regards

**Comment by skjnldsv** [comment]
Please don't use this repository in production. stable20 will and have received further changes since #321. SO the branch differs from the 20.0.8 release.
Please make sure you have the exact files from the 20.0.8 update tarball and make sure to clear your cache! :)
