### ISSUE TITLE
Editing PDF forms (and saving the results back to Nextcloud)?

### ISSUE THREAD

**Issue by tohojo** [nextcloud/files_pdfviewer#354]
It seems the upstream pdf.js supports editing and saving PDF forms (with saving added in v2.6.347). Any chance of supporting this in Nextcloud? I suppose adding the support to the viewer is just a matter of updating the pdf.js version, but maybe more work is needed to support saving? Not sure how this works, exactly...

**Comment by alexanderdd** [comment]
I am surprised only 8 people gave :+1: 

Ideally, this issue should be resolved. But in the meantime: 

Is there a way to tell pdf.js that it should not make the form fields fillable? This wrongly suggests to the user that you can fill the form - bad UX - can someone make the designers/UX people of Nextcloud aware of this?

**Comment by alexanderdd** [comment]
Here is a screencast showing the problem on NC 27.1.3, pdfviewer 2.8.0

There is no way for the user to know that the entered data will not be saved. To the user, the lack of a save button does not  mean it will not be saved, a lot of applications use auto-save.

![Peek 2023-11-03 11-10](https://github.com/nextcloud/files_pdfviewer/assets/28591861/29fed754-8048-4eca-913b-cffcf4387822)

**Comment by danxuliu** [comment]
Saving forms will be possible in Nextcloud 28 thanks to https://github.com/nextcloud/files_pdfviewer/pull/787

For Nextcloud 27 the forms will be shown as read-only with https://github.com/nextcloud/files_pdfviewer/pull/849

**Comment by alexanderdd** [comment]
Just tested it on Firefox 125.0.3, on both NC 28.0.3 and NC 29.0.0 (cloud.nextcloud.com) the situation is still like in the screencast above (entered data not saved) https://github.com/nextcloud/files_pdfviewer/issues/354#issuecomment-1792173435

reopen @szaimen ?

**Comment by alexanderdd** [comment]
never mind, it works now in NC 29, thank you!
