### ISSUE TITLE
PDF ansi wrong fonts

### ISSUE THREAD

**Issue by SkyRimin** [nextcloud/files_pdfviewer#355]
### Steps to reproduce
1. when Open/View pdf file (ansi) , fonts wrong coding, or black sqr. ( web browser - Chrome, Opera)

### Actual behaviour
When Open/View pdf file in browser (ansi) , fonts wrong coding, or black sqr

### Server configuration

Nextcloud on Hetzner Provider .

**Comment by skjnldsv** [comment]
Hey!
I wonder if that isn't the fault of the browser :)
Can you search for existing potential issues on the pdf.js repo? :thinking:

**Comment by szaimen** [comment]
Closing due to no response
