### ISSUE TITLE
"Missing PDF file" errors after NextCloud upgrade 21.0.1 -> 21.0.2

### ISSUE THREAD

**Issue by Infogeekx** [nextcloud/files_pdfviewer#383]
PDF.js v2.5.207 (build: 0974d6052)

**Comment by hobbsecky** [comment]
Same here.

**Comment by Synochy** [comment]
Same problem here migrating from Nextcloud 21.0.1 to 21.0.2

**Comment by thom7e** [comment]
Same Problem here after migrating to 21.0.2

**Comment by beardhatcode** [comment]
Duplicate of #381
