### ISSUE TITLE
pdf viewer cannot open file from SMB/CIFS external storage.

### ISSUE THREAD

**Issue by jpmv27** [nextcloud/files_pdfviewer#393]
### Steps to reproduce
1. Open pdf file from an SMB/CIFS external storage

### Expected behaviour
PDF viewer should show the file
(Works in 20.0.9, and in 20.0.10 with a pdf not from external storage)

### Actual behaviour
PDF viewer reports that it cannot open the file.
(Started after upgrade to 20.0.10)

### Server configuration

**Operating system**:
Linux 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache 2.4.6-97.el7.centos

**Database:**
PostgreSQL 13.3-1PGDG.rhel7

**PHP version:**
7.3.28-1.el7.ius

**Nextcloud version:** (see Nextcloud admin page)
20.0.10

**Where did you install Nextcloud from:**
Upgrade from 20.0.9 (Stable channel)

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - apporder: 0.12.0
  - audioplayer: 3.1.0
  - bookmarks: 4.2.1
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - emlviewer: 0.0.21
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - news: 15.4.4
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_script: 1.5.1
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - recommendations
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.11.12.4",
            "cloud.int.jpmvrealtime.com",
            "cloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/10.11.12.4\/nextcloud",
        "dbtype": "pgsql",
        "version": "20.0.10.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "log_rotate_size": 1048576,
        "app_install_overwrite": [
            "calendar",
            "emlviewer"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**
Firefox 88.0.1

**Operating system:**
Windows 10

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by beardhatcode** [comment]
Hi @jpmv27, does opening images and videos in the viewer still work? If so, this might be related to issue #381, could you test if its solution (PR #384) resolves this issue for you? To do this, replace
`apps/files_pdfviewer/js/files_pdfviewer-main.js` on your instance with [this file from that PR](https://raw.githubusercontent.com/nextcloud/files_pdfviewer/6d81ffbb65c3758bece144e0aff07b4a0ad20eef/js/files_pdfviewer-main.js). Clear your browser's cache and try to open pdfs again.

**Comment by jpmv27** [comment]
Thank you @beardhatcode, that resolved the issue.
I did see that issue before I opened this one, but overlooked the fact that there are spaces in the paths of the PDFs I tried to open.

**Comment by beardhatcode** [comment]
Happy to hear that your issue has been resolved.
