### ISSUE TITLE
PDF does not show when pathname contains a space

### ISSUE THREAD

**Issue by erikfdev** [nextcloud/files_pdfviewer#399]
### Steps to reproduce
1. In nextcloud create a folder with a space in its name
2. put a PDF file in that folder.
3. Try to open the PDF file using the pdfviewer.

### Expected behaviour
The PDF contents should be shown

### Actual behaviour
The error message 'missing PDF file' appears in a red box. When clicking the button More information, following text is shown:
PDF.js v2.4.456 (build: 228a591c)
Message: Missing PDF "https://invara-erde.freeddns.org/remote.php/dav/files/supererik/User/varia/parochie/zondagsvieringen/jaar%2520C/GEBEDSVIERING%2520St.%2520-%2520Cecilia%2520n-boekje.pdf".

I would expect to have %20 in the  pathname, not %2520 .

### Server configuration

**Operating system**:
Linux Mint 20.1
**Web server:**
Apache
**Database:**
SQLite
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
PHP 7.4.3 
**Where did you install Nextcloud from:**
web based upgrade of earlier versions

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by skjnldsv** [comment]
Fixed already, please search for existing issues :)
