### ISSUE TITLE
Fails to display PDF with a space in the name

### ISSUE THREAD

**Issue by lp-unaape** [nextcloud/files_pdfviewer#401]
### Steps to reproduce
1. Upload a PDF file with a space in the name
2. From the file application, click on the PDF file
3.

### Expected behaviour
Display of the PDF file

### Actual behaviour
Error message from pdf.js as shown in screen shot
![pdf0](https://user-images.githubusercontent.com/61372664/119869952-21649d00-bf21-11eb-8bdb-fd6ed5b047b6.png)
![pdf1](https://user-images.githubusercontent.com/61372664/119869973-26c1e780-bf21-11eb-95f1-a2c0148ccd45.png)

### Steps to reproduce
1. Upload a PDF file with a space in the name
2. From the file application, click on the PDF file
3.

### Expected behaviour
Display of the PDF file

### Actual behaviour
Error message from pdf.js as shown in screen shot

## Server configuration detail

**Operating system:** Linux 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (fpm-fcgi)

**Database:** pgsql PostgreSQL 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, pdo_pgsql, pgsql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 21.0.2 - 21.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated since several years

**Where did you install Nextcloud from:** Nextcloud tarball

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - announcementcenter: 5.0.0
 - apporder: 0.12.0
 - bruteforcesettings: 2.1.0
 - calendar: 2.2.2
 - circles: 0.21.2
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.4.2
 - external: 3.8.1
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.11.0
 - files_automatedtagging: 1.11.0
 - files_external: 1.12.0
 - files_pdfviewer: 2.1.0
 - files_retention: 1.10.1
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - forms: 2.2.4
 - groupfolders: 9.0.1
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - maps: 0.1.8
 - nextcloud_announcements: 1.10.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - photos: 1.3.0
 - polls: 1.8.3
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - rainloop: 7.1.2
 - recommendations: 1.0.0
 - richdocuments: 4.1.1
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - socialsharing_diaspora: 2.2.0
 - socialsharing_email: 2.2.0
 - socialsharing_facebook: 2.2.0
 - socialsharing_twitter: 2.2.0
 - spreed: 11.2.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.13.6
 - terms_of_service: 1.7.0
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_totp: 6.0.0
 - twofactor_u2f: 6.1.0
 - updatenotification: 1.11.0
 - user_external: 2.0.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflow_script: 1.6.0
 - workflowengine: 2.3.0
Disabled:
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "*************"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "21.0.2.1",
    "overwrite.cli.url": "https:\/\/hermes.unaape.asso.fr\/",
    "htaccess.RewriteBase": "\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "******",
                993,
                "ssl",
                "********"
            ]
        }
    ],
    "default_language": "fr",
    "force_language": "fr",
    "default_locale": "fr_FR",
    "force_locale": "fr_FR",
    "default_phone_region": "FR",
    "defaultapp": "apporder",
    "app.mail.accounts.default": {
        "email": "%USERID%@*********",
        "imapHost": "******",
        "imapPort": 993,
        "imapUser": "%USERID%@*********",
        "imapSslMode": "ssl",
        "smtpHost": "**********",
        "smtpPort": 587,
        "smtpUser": "%USERID%@*************",
        "smtpSslMode": "tls"
    },
    "updater.release.channel": "stable",
    "maintenance": false,
    "loglevel": 2,
    "app_install_overwrite": [
        "announcementcenter",
        "issuetemplate"
    ],
    "knowledgebaseenabled": false
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** IMAP

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0

**Operating system:** KDE NEON 5.21

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by timmwille** [comment]
Ah this gives some explanation, thx. Have the same bug in our organisations cloud. 

PDF Viewer 2.1.0
Nextcloud 21.0.2

**Comment by mokkin** [comment]
I can confirm this on Nextcloud 21.0.2 on PHP 7.4.3 on Ubuntu 20.04.

**Comment by Commifreak** [comment]
I can confirm this since a few days / last update of the cloud..?

PHP: 7.4.18
NC: 20.0.10

**Comment by skjnldsv** [comment]
Fixed already, wait for the next update
Sorry for the inconvenience
