### ISSUE TITLE
PDF-viewer hidden if window width too small

### ISSUE THREAD

**Issue by christianhauff** [nextcloud/files_pdfviewer#41]
### Steps to reproduce
1. Open a PDF-Document
2. Reduce browser window's width (in my case below 770px, e.g. if I move the window on half of my laptop's screen)
3. PDF-Viewer disappears, NC-Header-Bar stays

### Expected behaviour
The PDF-Viewer should still be shown

### Actual behaviour
The PDF-Viewer disappears

### Server configuration

**Operating system**:
Centos 6.9

**Web server:**
Apache 2.2.15

**Database:**
mysql 5.1.73

**PHP version:**
PHP 7.0.21

**Nextcloud version:**
12.0.0

### Client configuration
**Browser:**
Chrome+Firefox

**Operating system:**
Win7, Win10, Ubuntu

#### Nextcloud log
nothing related

#### Browser log
nothing related

**Comment by andreasjacobsen93** [comment]
Should be fixed in https://github.com/nextcloud/files_pdfviewer/pull/36

**Comment by christianhauff** [comment]
Sorry for the late answer, it's fixed! Thanks!
