### ISSUE TITLE
PDF View cannot display files with spaces or non-url safe characters in directory or file name

### ISSUE THREAD

**Issue by sseide** [nextcloud/files_pdfviewer#421]
### Steps to reproduce
1. upload file with a space in its name (or directory with space or german umlaut or similar)
2. try to open file with integrated PDF viewer
3. File is not shown, only error message

### Expected behaviour
file should be opened and displayed

### Actual behaviour
pdf view starts but displays error message only, generated https request to the file is giving a HTTP 404.

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4.3-4ubuntu2.4

**Nextcloud version:** (see Nextcloud admin page) 2.0.10

**Where did you install Nextcloud from:** HansonIT preconfigured VM

**List of activated apps:**
PDF Viewer 2.0.1

### Client configuration
**Browser:** Firefox and Chrome latest

**Operating system:** Linux, MacOS, Windows, ...

Wenn clicking in the webui on a pdf the integrated pdf view opens and gives the following eror message with an HTTP 404:
```
PDF.js v2.4.456 (build: 228a591c)
Message: Missing PDF "https://my.server.ip/remote.php/dav/files/myuser/stuff/Ausbau%2520Sch%25C3%25B6n/210120%2520KOSTENSCH%25C3%2584TZUNG.pdf".
```
Modifying the url to remove every "25" from the encoded chars i can access the file -> Nexcloud is DOUBLE encoding the path to load a file!

This one works (manually modifyed Url):
"https://my.server.ip/remote.php/dav/files/myuser/stuff/Ausbau%20Sch%C3%B6n/210120%20KOSTENSCH%C3%84TZUNG.pdf"

Using Nextcloud 20.0.10
PDF Viewer 2.0.1

Only solution so far: deactivate app "PDF Viewer".

#### Nextcloud log (data/owncloud.log)
nothing server-side found

#### Browser log
only http 404 for invalid url accessed by pdf viewer

**Comment by skjnldsv** [comment]
See other threads, it's fixed but not released

**Comment by nexxxxen** [comment]
Same problem on  20.0.10 from Official-Nextcloud-VM (installed one day ago and only updated).
¿Not released? ¿what other threads? ¿Would you be so kind as to indicate a link to the solution, fix, patch or whatsoever named trick? 

Thanks!
