### ISSUE TITLE
Opening file with whitespaces fails

### ISSUE THREAD

**Issue by cscholz** [nextcloud/files_pdfviewer#440]
### Steps to reproduce
1. Open a PDF file in the viewer app to ensure the file can be displayed correctly
2. Rename a pdf file to contain one or multiple white spaces
3. Open the file again. The error should occur

### Expected behaviour
Viewer app should be able to open files containing whitespaces in the filename

### Actual behaviour
File is reported as missing from pdf viewer in the browser

```
PDF.js v2.5.207 (build: 0974d6052)
Message: Missing PDF "https://cloud.domain.tld/remote.php/dav/files/USERNAME/FOLDER1/FOLDER2/FOLDER3/FOLDER4/[YYY-MM-DD]%2520-%2520FILE%2520NAME.pdf".
```

### Server configuration

**Operating system**:
Debian GNU/Linux 10 (buster)

**Web server:**
 nginx-full                            1.14.2-2+deb10u

**Database:**
mariadb-server-10.3                   1:10.3.29-0+deb10u1

**PHP version:**
 php8.0-fpm                            8.0.7-1+0~20210604.20+debian10~1.gbp7cd340

**Nextcloud version:** (see Nextcloud admin page)
21.0.2.1

**Where did you install Nextcloud from:**
Official nextcloud site

**List of activated apps:**
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - camerarawpreviews: 0.7.11
  - checksum: 1.1.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - duplicatefinder: 0.0.8
  - end_to_end_encryption: 1.7.1
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - impersonate: 1.8.0
  - lookup_server_connector: 1.9.0
  - oauth2: 1.9.0
  - photos: 1.3.0
  - provisioning_api: 1.11.0
  - rainloop: 7.1.2
  - richdocuments: 4.1.2
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_email: 2.0.0
  - twofactor_nextcloud_notification: 3.1.2
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0

### Client configuration
**Browser:**
Microsoft Edge

**Operating system:**
Windows 10 20h2

**Comment by skjnldsv** [comment]
Hey, this is fixed already, wait for upcoming releases.
Please use search next time :wink:

**Comment by Patrick-DE** [comment]
See https://github.com/nextcloud/files_pdfviewer/issues/381#issuecomment-845806364 for the fix

**Comment by cscholz** [comment]
As I understood the fix have already been pushed
