### ISSUE TITLE
Problems after update to 21.0.3

### ISSUE THREAD

**Issue by d-enai** [nextcloud/files_pdfviewer#442]
I updated yesterday to the new release 21.0.3
I uploadet a PDF.
When I tried to open itg I got this error message.
Fehler
cURL error 3: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for /hosting/discovery
This error was fixed in older versions.
Everything works fine until this update.

Best Andreas

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

I will also need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by rolpro** [comment]
Hi!

I have the same Issue here.
Thought i copy my Code here, because d-enai did not reply to your post.

**Comment by rolpro** [comment]
[media.rolandstrahlhofer.at-1630423745855.log](https://github.com/nextcloud/files_pdfviewer/files/7085088/media.rolandstrahlhofer.at-1630423745855.log)

**Comment by rolpro** [comment]
![Bildschirmfoto 2021-08-31 um 17 19 34](https://user-images.githubusercontent.com/4466537/131531603-38ac9ab6-13af-4a52-9009-7d6eab7ca5e0.png)

**Comment by santosh-goundar** [comment]
having same issue, after updating to 22.2.3, getting error refused to connect after trying to view the pdf

**Comment by santosh-goundar** [comment]
its with all pdf files, same issue with if has space in name or not, and it has resolved after updating to 22.2.5

**Comment by skjnldsv** [comment]
Good to know!
Thanks for the update :)
