### ISSUE TITLE
NC12, pdf.js "invalid top-level pages dictionary"

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/files_pdfviewer#45]
Hello,

i have many pdf files, nextcloud can't open:

![image](https://user-images.githubusercontent.com/1249295/31610465-756da0b8-b278-11e7-80fc-5b1ae1ce0083.png)

Other (pdf) files are ok (for example, if i create one with Word 2013). "PDF Creator" was "Nuance PDF Create". If i open the pdf's with the browser or a reader everything works. But NextCloud 12.0.3 shows the error.

There are no errors in the nextcloud.log if i open such a pfd.

Any ideas?

Because the pdf is not copyfree i cant upload a file.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
