### ISSUE TITLE
Error   Failed to open the requested file.

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/files_pdfviewer#528]
##### Some speculative statements are included in the following numbered list.
1. Install a Nextcloud server instance on a Virtualmin managed virtual server subdomain on a Ubuntu 18.04 machine and the same machine running MariaDB with the most recent version of NC in October of this year.
2. Run the system without trouble for months.
3. Install a couple of new apps like "[Google integration](https://apps.nextcloud.com/apps/integration_google)", "[OneDrive integration](https://apps.nextcloud.com/apps/integration_onedrive)", and "[Office Online integration](https://apps.nextcloud.com/apps/officeonline)". A suspicious app that was installed before noticing the problem then removed after noticing the problem was "[Temporary files lock](https://apps.nextcloud.com/apps/files_lock)". _Also, that app did not work like I thought it would._
4. Notice that PDF's won't open anymore and freak out.
5. Freak out and try opening both shared PDF files and directly owned files, and with different user accounts. Also, try files newly created vs. updated vs older files vs files defaulted by Nextcloud install.
6. Try a bunch of things that don't help like rebooting the server, trying it on different client OS's and other user accounts.
7. Start uninstalling recently installed apps, and freak out again leading to the reuse of step 5.
8. Also note that a second Nextcloud instance on the same physical machine which stores data on a MySQL based server does not have this problem.
9. Freak out and finally log this issue.

### Expected behaviour
Clicking on a PDF file opens the PDF for viewing in the browser.

### Actual behaviour
The error message is in the title of this issue, and the following screen is thrown.
![Screenshot from 2021-12-26 18-05-56](https://user-images.githubusercontent.com/28640985/147422188-22b804a1-86a5-42a8-9de9-f965906ebcfc.png)

#### Note, it's a MariaDB database in the Server Configuration report, not a `mysql` database.
**Link:** [System information](https://service.harrogatesquare.com/index.php/s/weRZHX4odiYZEiL)
**Password:** `tApNk6MGci`

**Where did you install Nextcloud from:** Fresh install plus one upgrade.

### Client configuration
**Browser:** Both Firefox and Chrome on both Ubuntu 20.04 workstation and Windows 11.

**Operating system:** Both Ubuntu 20.04 workstation and Windows 11.

#### Nextcloud log (data/owncloud.log)
[nextcloud.log](https://github.com/nextcloud/files_pdfviewer/files/7777722/nextcloud.log)

#### Apache Log
[sd_bad-fqdn_tld_access.log](https://github.com/nextcloud/files_pdfviewer/files/7777725/sd_bad-fqdn_tld_access.log)

#### Apache Error Log
[sd_bad-fqdn_tld_error.log](https://github.com/nextcloud/files_pdfviewer/files/7777726/sd_bad-fqdn_tld_error.log)

#### Browser log
```
nope
```

**Comment by WNYmathGuy** [comment]
I don't know if this helps or just adds a "red-herring", but...
Another item that doesn't preview in the browser as it did a short time ago is plain MP4 videos, where a video player is displayed, but the content doesn't show (video is black-screen but audio streams normally).

**Comment by WNYmathGuy** [comment]
Adding to that last comment, I get the same error message thrown for a simple `*.CSV` file. I'm not sure what a comma-separated-values file would have opened like before, but I assumed that files either rendered in the browser, or downloaded when clicked.

**Comment by ntovarsolorzano** [comment]
I have this same problem. 
1) $ php --version
```
PHP 8.0.13 (cli) (built: Nov 19 2021 21:51:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies
```

2) $ cat /etc/os-release
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

3) Running on docker container. The host OS is Ubuntu: 
$ cat /etc/os-release
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

4) cd /var/www/nextcloud/ cat version.php 
```
<?php
$OC_Version = array(23,0,0,10);
$OC_VersionString = '23.0.0';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array (
  'nextcloud' =>
  array (
    '22.2' => true,
    '23.0' => true,
  ),
  'owncloud' =>
  array (
    '10.5' => true,
  ),
);
$OC_Build = '2021-11-26T20:54:42+00:00 0619207f13792250aea775a2c3133d41ab625980';
$vendor = 'nextcloud';
```
5) Installed Apps: 
```
Accessibility	1.9.0		
Activities for shared file downloads	1.12.0		
Activities for shared file downloads, visible to all admins	1.11.0		
Activity	2.15.0		
Admin notifications	1.0.2		
Appointments	1.11.10		
Auditing / Logging	1.13.0		
Brute-force settings	2.3.0		
Calendar	3.0.4		
Circles	23.0.0		
Collabora Online	5.0.1		
Collaborative tags	1.13.0		
Comments	1.13.0		
Contacts	4.0.7		
Contacts Interaction	1.4.0		
Dashboard	7.3.0		
Deck	1.6.0		
Deleted files	1.13.0		
Federation	1.13.0		
File access control	1.13.0		
File sharing	1.15.0		
First run wizard	2.12.0		
Flow Upload	1.1.3		
Forms	2.4.0		
Google integration	1.0.6		
Log Reader	2.8.0		
Mail	1.11.5		
Monitoring	1.13.0		
Nextcloud announcements	1.12.0		
Notes	4.2.0		
Notifications	2.11.1		
Office Online integration	1.1.1		
OneDrive integration	1.1.2		
ONLYOFFICE	7.2.1		
Password policy	1.13.0		
PDF viewer	2.4.0		
Photos	1.5.0		
Pico CMS	1.0.16		
Privacy	1.7.0		
Quota warning	1.13.0		
Ransomware protection	1.12.0		
Recommendations	1.2.0		
Right click	1.2.0		
Share by mail	1.13.0		
Social sharing via email	2.4.0		
Support	1.6.0		
Text	3.4.0		
Theming	1.14.0		
TimeManager	0.2.6		
Twitter integration	1.0.2		
Update notification	1.13.0		
Usage survey	1.11.0		
User status	1.3.1		
Versions	1.16.0		
Video player	1.12.0		
Weather status	1.3.0		
Workflow OCR	1.23.1		
Default encryption module	2.11.0		
End-to-End Encryption	1.8.1		 
External storage support	1.15.0		
LDAP user and group backend	1.13.0		
```

Please, let me know if I'm missing something. 
I haven't even installed the SSL yet

**Comment by WNYmathGuy** [comment]
> 5\. Installed Apps:

Just wondering if you had installed and removed the Temporary Files Lock app?
Or do you operate with a MariaDB backend?

**Comment by ntovarsolorzano** [comment]
> > 5. Installed Apps:
> 
> Just wondering if you had installed and removed the Temporary Files Lock app? Or do you operate with a MariaDB backend?

No, I have not installed nor removed the Temporary Files Lock app. 
I do operate with MariaDB backend though.

**Comment by ntovarsolorzano** [comment]
One more thing that could be, (I don't know much about this)
The architecture of my machine is ARM. Could that be a thing?

**Comment by WNYmathGuy** [comment]
> The architecture of my machine is ARM. Could that be a thing?

I'm all Debian as I understand with the Ubuntu server. I know personally firsthand that MariaDB diverged with SQL syntax from MySQL. I suspect a bunch of things, quirky problems, may be caused by MariaDB. I have 2 Nextcloud instances on the same Ubuntu server, but one reaches to a MySql server inside the LAN, and the other uses the MariaDB on the same metal. Only the MariaDB is having this problem.

Weird issues I reported lately seem like they could be caused by defaults to be different; e.g. `*_ci` vs. case-sensitive tables and fields.

**Comment by squier2308** [comment]
Same issue here. What's odd: It did work quite a time after the installation and seemed to stop working out of nowhere. Working on MariaDB, too and I am not sure whether my hosting provider could have changed from mysql to MariaDB without my knowledge?

**Comment by WNYmathGuy** [comment]
> not sure whether my hosting provider could have changed from mysql to MariaDB without my knowledge?

I would like to doubt that, but who knows. Years ago, one of my systems (maybe Moodle or Friendica) was pressuring new instances to prefer MariaDB because of the alterations in the license agreements for MySQL. I switched over my new bigger server during a major migration and discovered that Nextclouds MySQL data dump would never convert right into MariaDB, so I used the old server to make an internal MySQL stand-alone server and that older Nextcloud instance has been fine ever since..

**Comment by WNYmathGuy** [comment]
I honestly don't know when things started working again or why, but my viewer is working again, both PDF's andMP4's. 

Since my last comment was 4 day's ago, I assume I would have tested it again since then, but I don't know what the date is when I last knew it to be non-working. Last night somebody at an in-person meeting opened a PDF and I was shocked that it was working. PHP just did updates recently. I always stay current with other apps on Nextcloud. 

Baffled by why it stopped and why it started working again.

I guess if other people on this issue say theirs is working again, it can get marked closed.

**Comment by skjnldsv** [comment]
> Baffled by why it stopped and why it started working again.

We did lots of dependencies updates :)
Most likely part of this :rocket:
