### ISSUE TITLE
When in Dashboard, App throws JavaScript Error for registering viewer handler

### ISSUE THREAD

**Issue by StefCGN** [nextcloud/files_pdfviewer#542]
Hi,
the App throws a JavaScript Error, when entering the Dashboard.

![2022-01-18 11_23_13-Dashboard - Kreyenborg koeln - Cloud — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/149919146-73de0661-5d0f-4513-9397-4361634699e2.png)

**Comment by eneiluj** [comment]
Hi, thanks for the issue. This has been fixed in ff256250399f78953c41e6df6f289719e7def844

**Comment by StefCGN** [comment]
Hi,
thanks for letting me know.
But it's not in the current version of the app.
How do I get the new version?
