### ISSUE TITLE
popup menu on top-right-menu hidden

### ISSUE THREAD

**Issue by schiessle** [nextcloud/files_pdfviewer#558]
Tested on c.nc.com (version 23.0.1)

The PDF viewer has a "..." menu at the top right. When I click on it I just see a small arrow at the top but the actual popup menu isn't visible:

![grafik](https://user-images.githubusercontent.com/1589737/151869385-a7705f0e-3235-4ebb-857c-fafdbc69e4d2.png)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/files_pdfviewer/issues/559
