### ISSUE TITLE
PDF.js => Setting up fake worker failed: Cannot load script pdf.worker.js + FIX

### ISSUE THREAD

**Issue by mrAceT** [nextcloud/files_pdfviewer#560]
### Steps to reproduce
1. click on an PDF in Documents..

### Expected behaviour
Mee not seeing an error bot the contents of the PDF

### Actual behaviour
The frame opens (black barr, pdf name, zoom options) An in stead pof the file I see this error
```
PDF.js v2.9.359 (build: e667c8cbc)
Message: Setting up fake worker failed: "Cannot load script at: https://cloud.knoopbeheer.nl/apps/files_pdfviewer/js/pdfjs/build/pdf.worker.js?v=2.3.1".
```

### Server configuration
**Operating system**: AlmaLinux 8
**Web server:** Apache
**Database:** Mysql
**PHP version:** 7.4
**Nextcloud version:** 22.2.4
**Where did you install Nextcloud from:** original
**List of activated apps:**
```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - apporder: 0.14.0
  - calendar: 3.0.5
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.7
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - deck: 1.5.5
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupquota: 0.1.7
  - keeweb: 0.6.8
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.6
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - richdocumentscode: 21.11.103
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.3
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - user_usage_report: 1.6.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_pdfviewer: 2.3.1 (I have now disabled it..)
  - user_ldap
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.4.3",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***l",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "nl",
        "default_phone_region": "NL",
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "versions_retention_obligation": "7, auto",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Client configuration
**Browser:** Version 97.0.4692.99 (Official Build) (64-bit)
**Operating system:** Windows 10

#### Nextcloud log (data/owncloud.log)
```
no strange things there (it's a JavaScript error..)
```

#### Browser log
```
Opening viewer for file  /Nextcloud Manual.pdf
index.js:314 OC.requestToken changed xxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
index.js:314 OC.requestToken changed yyyyyyyyyyyyyyyyyyyyyyyyyyy=
```

**Comment by mrAceT** [comment]
![after opening pdf](https://www.knoop.frl/img/nextcloudpdf1.jpg)

In the log there isn't much I found of interest: (the log is extremely long, but couldn't find a way to create a "read more" and wasn't able to post it, here a link) (please let me know if you've got it, then I'll remove it)
https://www.knoop.frl/img/1643967415250.log

**Comment by skjnldsv** [comment]
I can access https://cloud.knoopbeheer.nl/apps/files_pdfviewer/js/pdfjs/build/pdf.worker.js?v=2.3.1
For me this looks like a setup issue or browser.

Can you try with a different browser? Or in a private tab to make sure no extensions are loaded?

**Comment by mrAceT** [comment]
Indeed, Chrome seems to be the problem!
In a private tab the problem is still there, but in a different browser (Edge) the PDF loads!

When I find the time to test which extension is the problem I'll post it here (so please do not yet close this issue; as that might help others)

PS: @skjnldsv, I'dd appreciate it if you'dd remove the (deep) link to my NextCloud instance.

**Comment by mrAceT** [comment]
@skjnldsv, even when I start Chrome with --disable-extensions --disable-plugins I get the error.

So I started FireFox (which I rarely use, so is quite 'maiden') there de debugger gave me a good clue!

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://cloud.[domain]/apps/files_pdfviewer/js/pdfjs/build/pdf.worker.js?v=2.3.1 (“worker-src”).```

Now knowing where to look for, I also found something similar in Chrome.

I have a quite strict setup.. in the past I have added the **security policy** ''blob' for 'worker-src'. Apparently at some point it got necessary to add **'self'** also.

I have done this now and the PDF loads perfectly again!

NOTE: Edge apparently  dos not listen correctly to the security policy settings....

**Comment by skjnldsv** [comment]
> I have a quite strict setup.. in the past I have added the **security policy** ''blob' for 'worker-src'. Apparently at some point it got necessary to add **'self'** also.

is it overrided? Nextcloud manage CSP by itself, we allow workers in some specific areas.
`files_pdfviewer` handle this case already. You should not have to change this config or edit those csp yourself.
https://github.com/nextcloud/files_pdfviewer/blob/fd26080dc2000b9e13aed41dc35e9dcbf64558e6/lib/Controller/DisplayController.php#L67-L73

**Comment by nursoda** [comment]
I just also ran into this, for both shared public link and as internal user.

Server: NC24b2 on Arch served by NGINX and PHP-FPM, unmodified CSP, usint [this nginx-Template](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html).

Client: Current FX w/ uBlockOrigin and Chrome w/o. But even with uBlockOrigin completely deactivated, I can only view PDFs when disabling the files_pdfviewer app.

@mrAceT WHERE did you add 'self' to the CSP?

**Comment by mrAceT** [comment]
@nursoda, I have a rather strict SSL configuration in Apache, I added that 'self' to the vhost config of that account

**Comment by luck3rhoch3** [comment]
Hey guys,

i have the same error and i tried every single browser that's available in the internet...

It happens since updating to nc version 24 and php 8.1. I tried downgrading php to 7.4 but then i get an internal server error.

Here is the log:
![error](https://user-images.githubusercontent.com/57688233/162040265-53742079-b7bb-455d-9fac-d98252819682.png)
![browser_console](https://user-images.githubusercontent.com/57688233/162040270-7301da29-ead2-4d3f-9750-bf62080597f1.png)

**Comment by skjnldsv** [comment]
Yes, fixed on latest
