### ISSUE TITLE
Add more features like draw, add text, highlight text. Just like in the edge browser

### ISSUE THREAD

**Issue by S1M0NDOTCOM** [nextcloud/files_pdfviewer#562]
![image](https://user-images.githubusercontent.com/21236804/153728796-639f094c-f9c6-4d9c-bfa3-a233c1c726cd.png)

Thanks for your owesome nextcloud app

**Comment by skjnldsv** [comment]
Hi, we do not control the pdf viewing library.
This is on https://mozilla.github.io/pdf.js/ side :)
