### ISSUE TITLE
 Enable download button Secondary Toolbar

### ISSUE THREAD

**Issue by oghin7** [nextcloud/files_pdfviewer#570]
I have an issue with how can I enable the download button Secondary Toolbar public template view. 

nextcloud/apps/files_pdfviewer/templates/viewer.php

line 144

 <button id="secondaryDownload" class="secondaryToolbarButton download visibleMediumView" title="Download" tabindex="54" data-l10n-id="download" hidden="true">
              <span data-l10n-id="download_label">Download</span>
            </button>

I have changed with:
hidden="false"> 

its seen to be not showing the download button? Even I delete the hidden option. No result  Where else needs to change to enable the download button active?

**Comment by oghin7** [comment]
if someone can help this issue. thank you

**Comment by skjnldsv** [comment]
Hi, it's disabled on purpose.
You can enable download on the sharing option of your public share. There will be a big button on top of the page (blue header)

**Comment by oghin7** [comment]
Thank you for your reply. i understand the header button. Is there any away active the pdf viewer app. i was tried to  
 <button id="secondaryDownload" class="secondaryToolbarButton download visibleMediumView" title="Download" tabindex="54" data-l10n-id="download">
              
hidden="true"> has removed but not showing button. it is important for the client to download the pdf. we may have the option to enable and disable the button. pls, advise where i need to change to active it.
Thank you very much.

**Comment by skjnldsv** [comment]
You'll have to compile the app yourself
You cannot just edit the template
https://github.com/nextcloud/files_pdfviewer/blob/3fef33f5c2d1d9f53148450eb584f75f24c430db/src/workersrc.js#L65
