### ISSUE TITLE
comments in pdf viewer are overlayed with "NoIcon"

### ISSUE THREAD

**Issue by LPTT** [nextcloud/files_pdfviewer#571]
Hi,

I have the problem that comments/ annotations in my pdfs are all overlayed with:
![image](https://user-images.githubusercontent.com/8556564/156573575-e656c7bc-1e57-4ddb-8c3f-a4c66701cf8f.png)
(text translates to "Attachment: NoIcon")
If I download the pdf all is well. Log file does not show an error. Any ideas?

### Expected behaviour
opening files local with a pdf viewer looks like that
![Bildschirmfoto 2022-03-03 um 14 50 33](https://user-images.githubusercontent.com/8556564/156577833-53e370d5-c5ae-42dd-9b8a-2eb1f38ef549.png)

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
Windows and Macos
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
22.2.5
pdfviewer 2.3.1
**Where did you install Nextcloud from:**

**List of activated apps:**
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.6
  - carnet: 0.24.4
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - deck: 1.5.5
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.4
  - richdocumentscode: 21.11.103
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - support: 1.4.0
  - user_ldap
  - user_status: 1.1.1

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "***REMOVED SENSITIVE VALUE***\/cloud\/data\/tmp\/",
        "dbtype": "mysql",
        "version": "22.2.5.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "de",
        "maintenance": false,
        "has_rebuilt_cache": true,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}

### Client configuration
**Browser:**
Safari, Vivaldi, Chrome, Firefox
**Operating system:**
Win 10, MacOs Monterey
#### Nextcloud log (data/owncloud.log)
```
nothing is logged
```

#### Browser log
```
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. @ globals.js:62
Opening viewer for file  ***REMOVED***.pdf Viewer.vue:275
util.js:135 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment utils.js 135
```

**Comment by skjnldsv** [comment]
Does it work in https://mozilla.github.io/pdf.js/web/viewer.html ?

**Comment by LPTT** [comment]
yes it does work:
<img width="66" alt="image" src="https://user-images.githubusercontent.com/8556564/157117835-c64afd45-3893-42ec-b91a-f6378890fae2.png">

**Comment by LPTT** [comment]
any ideas?
