### ISSUE TITLE
After update new version PDF viewer 2.5.0 the download button gone

### ISSUE THREAD

**Issue by oghin7** [nextcloud/files_pdfviewer#607]
After updating the new version of PDF viewer	2.5.0 the download button 
can not find 
files_pdfviewer/src/workersrc.js
Line 65 in

 PDFViewerApplication.download = function() { 

Could you please help how to enable it?

thank you

**Comment by oghin7** [comment]
someone can help me I already enable the button on css file but showing. what needs to do workerscr.js.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/files_pdfviewer/issues/608
