### ISSUE TITLE
PDF viewer not working 

### ISSUE THREAD

**Issue by guideon** [nextcloud/files_pdfviewer#613]
I am facing many issues withe the PDF viewer and the File app in NC24 some files (ebooks from packtpub) are not recognized by NC and in addition to this they are not displayed via the iPhone mobile app.
On the pc if you click on one of them the pdf viewer does not work and you are redirected to a download to your PC instead. It seems to be a major bug. Regards.

### Server configuration

**Operating system**:
Debian 10
**Web server:**
Ubuntu
**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
NC24
**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by skjnldsv** [comment]
Please fill the template properly :)
