### ISSUE TITLE
Disable pdf viewer on files that have download disabled

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/files_pdfviewer#649]
We should not attempt to open the pdf viewer for files that have download disabled as it fails to download the file from webdav

Ref https://github.com/nextcloud/server/pull/32482#issuecomment-1218387463

**Comment by juliushaertl** [comment]
Related to the discussion we had @Raudius about making Collabora the default viewer in this case.

**Comment by elhananjair** [comment]
> Related to the discussion we had @Raudius about making Collabora the default viewer in this case.

Oh I wish if that's possible, specially for PDF files

**Comment by juliushaertl** [comment]
- [ ] Block opening pdf files with the disabled download permission
- [ ] Using collabora as a default just in this case is hard, as the viewer doesn't have proper logic for checking the file with custom callbacks at opening
  - [ ] We go for just registering Collabora as default for pdf if files_pdfviewer is disabled

**Comment by allexzander** [comment]
There is also an inconsistency in how "Allow download/Hide download" works with internal vs email shares. For email shares, there is a "Hide download" checkbox, which, while checked, allows the share-receiving user to view the PDF file without allowing to download it. The PDF viewer seems to be different for internal vs email share.

**Comment by strangmann** [comment]
Is there a workaround instead of using collabora? I will not switch to collabora now. The "Allow download"-function does not work anymore. Is it possible to switch to the "Hide download"-function?
