### ISSUE TITLE
App store page seems to be outdated

### ISSUE THREAD

**Issue by p-bo** [nextcloud/files_pdfviewer#685]
Looking on app page on apps.nextcloud.com : 

https://apps.nextcloud.com/apps/files_pdfviewer

it seems, that newer versions of app were not published for very long time there.

But app development is quite vivid (and releases tagged).

Would it be possible to check why app store page is not updated please?

Thanks :-)

**Comment by p-bo** [comment]
Strange thing is, that directly in app catalog on Nextcloud instance, everything is up to date.

**Comment by skjnldsv** [comment]
Hey!
The pdf viewer is now shipped with versions of Nextcloud, No updates are provided through the appstore anymore :)

**Comment by p-bo** [comment]
@skjnldsv Thanks for clarification - so if understood correctly, pdf viewer is now part of default Nextcloud install and updated with it, right?

So would it be possible to follow instructions on:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

and remove app page from appstore, because is not relevant any more please?

**Comment by skjnldsv** [comment]
Well, if you decide to setup Nextcloud 12 or 13, you then will not have the option to install pdf viewer :)

**Comment by AndyScherzinger** [comment]
> so maybe to schedule app store page removal to March 2023, to be on safe side?

Yes that would be safe to do

**Comment by SystemKeeper** [comment]
> Yes that would be safe to do

@AndyScherzinger Could we do this? :-)

**Comment by joshtrichards** [comment]
No longer necessary due to nextcloud/appstore#1561
