### ISSUE TITLE
Open PDF file and display blank

### ISSUE THREAD

**Issue by TwoDogs2** [nextcloud/files_pdfviewer#693]
Open PDF file and display blank
![image](https://user-images.githubusercontent.com/121689365/210506313-c77111df-9fce-41e8-bae4-e2908dcb3e58.png)
server 25.0.2
OS Centos7.8
PDF viewer 2.6.0
Please tell me how to deal with this

**Comment by skjnldsv** [comment]
The github template is muuuch more complex than the few data you entered above.
I'm a bit frustrated. Please take the proper time, I cannot do that for every issue opened on the reps I managed :confused: 

In any case, I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by skjnldsv** [comment]
Also, I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by TwoDogs2** [comment]
> The github template is muuuch more complex than the few data you entered above. I'm a bit frustrated. Please take the proper time, I cannot do that for every issue opened on the reps I managed 😕
> 
> In any case, I will need your browser console log to investigate this issue. Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
> 
> How to access your browser console (Click to expand)

Hi I have upgraded my browser and it is working normally Thank you very much
