### ISSUE TITLE
PDFs not shown due to mod_security on shared hosting

### ISSUE THREAD

**Issue by JboyJW** [nextcloud/files_pdfviewer#722]
### Steps to reproduce
1. Enable PDF_Viewer
2. Click any PDF to view it

PS. I'm on BlueHost shared hosting, it's still on PHP 7.4 and MySql 5.7, and it has mod_security activated and I can't change it to use DetectionOnly.

### Expected behaviour
The PDF should load in the PDF Viewer frame

### Actual behaviour
PDF Viewer frame shows but no PDF is shown. Looking at Console, it shows a 406 error and viewing the error shows: Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

### Server configuration
Operating system: Linux 4.19.150-76.ELK.el7.x86_64 #1 SMP Wed Oct 7 01:33:43 CDT 2020 x86_64
Webserver: Apache (litespeed)
Database: mysql 5.7.23
PHP version: 7.4.33
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, litespeed, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, exif, mysqlnd, odbc, PDO, pgsql, Phar, posix, pspell, SimpleXML, soap, sockets, sqlite3, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, xmlreader, xmlrpc, imagick, SourceGuardian, ionCube Loader, Zend OPcache
Nextcloud version: 25.0.2 - 25.0.2.3
Apps:
 - activity: 2.17.0
 - circles: 25.0.0
 - cloud_federation_api: 1.8.0
 - comments: 1.15.0
 - contactsinteraction: 1.6.0
 - dashboard: 7.5.0
 - dav: 1.24.0
 - federatedfilesharing: 1.15.0
 - federation: 1.15.0
 - files: 1.20.1
 - files_rightclick: 1.4.0
 - files_sharing: 1.17.0
 - files_trashbin: 1.15.0
 - files_versions: 1.18.0
 - firstrunwizard: 2.14.0
 - logreader: 2.10.0
 - lookup_server_connector: 1.13.0
 - nextcloud_announcements: 1.14.0
 - notifications: 2.13.1
 - oauth2: 1.13.0
 - password_policy: 1.15.0
 - photos: 2.0.1
 - privacy: 1.9.0
 - provisioning_api: 1.15.0
 - recommendations: 1.4.0
 - related_resources: 1.0.3
 - serverinfo: 1.15.0
 - settings: 1.7.0
 - sharebymail: 1.15.0
 - support: 1.8.0
 - survey_client: 1.13.0
 - systemtags: 1.15.0
 - text: 3.6.0
 - theming: 2.0.1
 - twofactor_backupcodes: 1.14.0
 - updatenotification: 1.15.0
 - user_status: 1.5.0
 - viewer: 1.9.0
 - weather_status: 1.5.0
 - workflowengine: 2.7.0

#### Browser log
a) The javascript console log
Failed to load resource: the server responded with a status of 406 ()
b) The network log
Reqeust URL: https://newpath.ca/board/index.php/apps/files_pdfviewer/?file=https://newpath.ca/board/remote.php/dav/files/User%20Name/New%20Path%20Services/Board%20Meeting%20Package/Board%20Agenda%20March%202023.pdf&canDownload=1
Parameters: file: https://newpath.ca/board/remote.php/dav/files/User Name/New%20Path%20Services/Board%20Meeting%20Package/Board%20Agenda%20March%202023.pdf
canDownload: 1
Response: An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.
```

**Comment by szaimen** [comment]
Hi, we cannot support any custom mod_security config. Please make sure to adjust mod_security so that the pdfviewer is not blocked.
