### ISSUE TITLE
Request: Ability to resize sidebar

### ISSUE THREAD

**Issue by JL102** [nextcloud/files_pdfviewer#725]
Hi,

Nextcloud is great and I'm really enjoying it! I'm quite impressed with the PDF viewer. Reminds me a lot of Okular, which I'm already used to. One small feature I'd really appreciate is the ability to resize the sidebar. In situations where there are many chapters in the PDF and the chapters are wordy, the thin sidebar causes the chapters to take up many lines at once, leading to a lot of scrolling being necessary to browse between chapters. If I could drag the sidebar to be wider in PDFs like these, then I would be able to more easily browse the chapters. 

![image](https://user-images.githubusercontent.com/11487870/231900750-1ed958b5-3662-4f5e-a5e0-1487e04244c3.png)

**Comment by JL102** [comment]
Is Nextcloud using an old version of pdf.js? I just checked the [online demo of pdf.js](https://mozilla.github.io/pdf.js/web/viewer.html), and the sidebar is resizable.

**Comment by szaimen** [comment]
Apparently this css e.g. https://github.com/nextcloud/files_pdfviewer/blob/master/js/pdfjs/web/viewer.css is not up-to-date.

@skjnldsv do you know if we need to update this file by hand to bring it in-line with the upstream file?

See https://github.com/nextcloud/files_pdfviewer/blob/master/js/pdfjs/web/viewer.css

**Comment by skjnldsv** [comment]
The js/pdfjs folder is the current version of pdfjs
It is fetch on build

https://github.com/nextcloud/files_pdfviewer/blob/7969be3ecbee2c15ad1862c2546953b3c396d393/package.json#L31
https://github.com/nextcloud/files_pdfviewer/blob/7969be3ecbee2c15ad1862c2546953b3c396d393/package.json#L18
https://github.com/nextcloud/files_pdfviewer/blob/7969be3ecbee2c15ad1862c2546953b3c396d393/pdfjs-get.js#L27

**Comment by szaimen** [comment]
> The js/pdfjs folder is the current version of pdfjs
> It is fetch on build

Ah, right, so are we maybe overwriting some values somewhere?

**Comment by JL102** [comment]
![image](https://user-images.githubusercontent.com/11487870/236088977-a20ec8f9-04ca-423d-82e6-e6e710792bc7.png)
Looks like the sizebarResizer element is there in the Nextcloud viewer, but it's being force-hidden for some reason.

**Comment by szaimen** [comment]
https://github.com/nextcloud/files_pdfviewer/blob/7969be3ecbee2c15ad1862c2546953b3c396d393/templates/viewer.php#L94

**Comment by JL102** [comment]
I see. That line was last modified in March 2020: 7d50bfd717f9175e5736710477b7636063b7e1c4

and PDF.js's viewer.html was then modified in September 2020, removing class="hidden": https://github.com/mozilla/pdf.js/commit/01c1d87171cd7d5a72edaedeb86360242d211ddb

**Comment by szaimen** [comment]
@skjnldsv apparently the viewer.php template does not get updated automatically. Is this by design?

**Comment by JL102** [comment]
Seems to me like it's non-trivial to update the viewer.php template automatically, as there's a sizeable handful of embedded `<?php` statements in the head, which appear to mostly be related to directing hrefs/links to wherever pdf.js's static assets are located on the Nextcloud server. 

viewer.html hasn't been updated in the past 3 years, so I'm guessing that it won't be updated very frequently in the future, so it wouldn't be too severe if someone just manually updates viewer.php every so often.

**Comment by szaimen** [comment]
Would you mind creating a pr for the sidebar?

**Comment by JL102** [comment]
Sure, I'll need to set up my development environment first to test and make sure everything works; I should be able to get to it in a few days

**Comment by JL102** [comment]
Oops, I completely forgot to do that - Thanks for taking care of it! 🤣
