### ISSUE TITLE
Cannot update from 1.2.0 to 1.2.1 on NC 13.0.1

### ISSUE THREAD

**Issue by awesome-manuel** [nextcloud/files_pdfviewer#73]
### Steps to reproduce
1. Install NC 13.0.1 with PDF viewer app 1.2.0
2. NC shows update hint for PDF viewer app
3. Update PDF viewer app to 1.2.1

### Expected behaviour
Update PDF viewer app is update to 1.2.1

### Actual behaviour
PDF viewer app stays at 1.2.0

### Server configuration

**Operating system**: Nextcloud Docker container

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** As in Docker container for NC 13.0.1

**Nextcloud version:** 13.0.1

**Where did you install Nextcloud from:** Docker

#### Nextcloud log (data/owncloud.log)
```
Error | PHP | Undefined index: @value at /var/www/html/lib/private/legacy/app.php#1172
```

**Comment by nRaecheR** [comment]
I can confirm this, same problem on a fresh installation of NC 13.0.1 with MariaDB 10.1, both as official Docker containers.
The Apps app keeps nagging about an update of the PDF viewer from 1.2.0 to 1.2.1 but the update doesn'r seem to work after I start it by clicking on the "Update to 1.2.1" button.

**Comment by freeeflyer** [comment]
Same here.

**Comment by Rathorian** [comment]
Same here :)

**Comment by PnjDbq** [comment]
Can confirm issue also exists with the official Snap.

**Comment by bsyd** [comment]
Is it related to nextcloud/docker#288 ?

**Comment by alexandre1985** [comment]
I'm on archlinux and I also can't update my nextcloud 13 pdf viewer from 1.2.0 to 1.2.1

**Comment by bleed2002** [comment]
same here, using wonderfall/nextcloud though

**Comment by rammjet** [comment]
Same here with docker.  Found the update in custom_apps.

Tried changing the owners on apps from www-data:root to www-data:www-data but didn't work.

Deleted files_pdfviewer in apps and moved the one from custom_apps to apps.  Refreshed and Nextcloud performed the update.  Now working.

**Comment by alexandre1985** [comment]
Where do I find the files_pdfviewer of custom_apps? I can't find a directory with that name...

**Comment by alexandre1985** [comment]
my problem seems that I have 2 apps directory only readonly (the one with the system default apps named "apps/") and the other read and write (for the apps that I install named "apps2/").
I have removed the apps/files_pdf_viewer, accessed nextcloud main page and it said something about an update, I clicked to update and it didn't finished the update successfully. Now after the unsuccessfull update it says that my nextcloud is in maintenence mode and I can't do anything with it. NEED HELP!

**Comment by rammjet** [comment]
@alexandre1985 Did you move files_pdfviewer from apps2/ to apps/?

**Comment by alexandre1985** [comment]
No. But now that my nextcloud is in "maintenence mode" I have moved the directory and still I can't make nextcloud work again, that is, get out of maintenence mode

**Comment by freeeflyer** [comment]
Well..
PDFViewer is tagged as "Official" so I think it should be in apps/ and not apps2/ (Maybe I'm wrong)
Additionally there are other applications in apps/ and they are updating fine.

If changing the "writable" flag for this directory does solve the problem and that my 1st point is right, I'm not sure it's a resolution, even if it's a lead to the real problem..

**Comment by alexandre1985** [comment]
@freeeflyer When I updated PDFViewer since the only writable directory was apps2/, Nextcloud put it in there while also maintaining the PDFViewer of app/ . I believe that is why it didn't appear as updated (but it was downloaded to app2/).

**Comment by freeeflyer** [comment]
ok.. Maybe the right place for it is apps2..
So it's not clear for me which app goes to apps and to apps2. 
Deleted the files_pdfviewer/ directory from apps/ reload nc, watched a short maintenance phase then it seems ok.

**Comment by alexandre1985** [comment]
apps/ and app2/ only exist on my configuration. apps/ is the default directory for your apps. If you have this directory the not updating problem may be from config/config.php not having this directory as writable => true in apps_path array

**Comment by godfuture** [comment]
Are system apps aka "official" not meant to be updated manually?

**Comment by alexandre1985** [comment]
I believe that the "system apps" and official apps may not be the same, dont know.
don't know I'm a user not a developer

**Comment by jonathanpantall** [comment]
We're running NC 13.0.0 and encountering this issue as well. Thanks ahead of time for looking into this!

**Comment by tYYGH** [comment]
Hi! I have kind-of apps and apps2 like alexandre1985, and I have the same problem (PDF viewer not upgrading to 1.2.1).

It seems to me, the problem is, that Nextcloud should **not** notify of updates to apps when:
* the application is official, and
* the app-store, where the application is, is configured as _non_-writable.

Or maybe Nextcloud should simply not notify of updates to non-writable apps…

What do you think?

**Comment by alexandre1985** [comment]
Its not a nextcloud issue, I believe that may be a misconfiguration in our part.
If you put on `config/config.php` on apps_path, the first element of the array to be the writable directory (may that be apps or apps2) the issue disappears.
Try it.

**Comment by godfuture** [comment]
@alexandre1985 
I tried it. I changed the order in the apps path array where 0 goes to custom apps as first element and 1 to default apps as second elment. Somehow it always reverts back, but I don't know why...and update still does not work for me.

**Comment by alexandre1985** [comment]
@godfuture I'm not a part of the Nextcloud team, I'm just a user, so I don't know the specifics of the program.
Did you try to click on Update PDFViewer on the Nextcloud Apps page?

**Comment by godfuture** [comment]
@alexandre1985 why do you keep repeating that you're a user? Am I suppose to answer only the Nextcloud team? A community is by its definition living from contribution. Answers surely belong to such...We post information here that everyone can profit from it.

Yes, I have tried to update it in the apps page. My feeling is that this happens only with the pdf viewer official app. It would be interesting to know, if such problems occurs also for other official apps.

**Comment by bsyd** [comment]
for those running wonderfall and waiting hopelessly for an update, please read this thread : 
https://github.com/Wonderfall/docker-nextcloud/pull/15
And maybe switch to https://hub.docker.com/r/benyanke/nextcloud/.

**Comment by tYYGH** [comment]
Removing the directory of the app should not be the solution.

In my case, I am not using a Docker image. I am simply using a package from the distribution, and the files are placed in /usr. Thus I have the app-dir in /usr declared read-only, and another app-dir under /var declared writeable.

I should not be expected to remove an app under /usr, just so that it can be upgraded under /var. So one of these must be chosen:

* Choice 1: Nextcloud allows an app to be present in several locations, and only the newer one would be loaded => in this case, the distribution app would remain identical until the next distribution upgrade, and live app updates would write newer version in a writeable location.
* Choice 2: Nextcloud forbids (and even hides) updates to apps that are in read-only locations.
* Choice 3: Nextcloud only shows updates to apps that are non-official, the official apps being considered part of a bundle that goes with the main engine and gets updated with the main engine.

**Comment by skjnldsv** [comment]
Cannot reproduce anymore
ALso updated master
