### ISSUE TITLE
Annotation collaboration

### ISSUE THREAD

**Issue by MarekPikula** [nextcloud/files_pdfviewer#75]
I think that it would be nice to have collaboration feature for annotations integrated with NextCloud. At the moment you have to download and annotate PDFs in desktop software, but the best would be to be able to collaboratively annotate and comment, as it is possible for Collabora documents.

**Comment by GithubWingi** [comment]
Have you come to find a way to do this ? I'm looking for this same feature at the moment ...

**Comment by MarPiRK** [comment]
Not really. I'm not too much of WebDev, so it's just feature proposal from my side.

**Comment by scaredmushroom** [comment]
Today I found something like this. It is a really young project. https://github.com/strukturag/pdfdraw
