### ISSUE TITLE
 PDF contains information but incomplete

### ISSUE THREAD

**Issue by sunshine7x** [nextcloud/files_pdfviewer#758]
I have NextCloud HUB 20.0.10 ( Shared server )
PDF Viewer 2.0.1

I'm facing a problem with a file type. When I upload to nextcloud, it appears incomplete. If I download it to my computer it works fine.

Viewing by PDF VIEWER: https://imgur.com/a/M7jv9HV
Viewing by Downloaded file: https://imgur.com/WAkXp48

If I try to print directly from the nextcloud pdf viewer I get this message:
"Warning: PDF is not fully loaded yet." : https://imgur.com/XcF0KaL

When I try to open the pdf file it keeps spinning this ball (the red arrow indicates)
https://imgur.com/KNwzWx3

Can anyone help me ?

**Comment by szaimen** [comment]
Hi, Nextcloud 20. is completely outdated. Please update to at least Nextcloud 25.0.7 and try again.

**Comment by sunshine7x** [comment]
Unfortunately, the most current version on the shared server is this: 20.0.10 .
Tried with other versions, 19 , 18 ,17 same problem.
