### ISSUE TITLE
Cant print PDF pages anymore after last update

### ISSUE THREAD

**Issue by 1tremer** [nextcloud/files_pdfviewer#77]
Hello, 

since the last update I cant print PDF files anymore. 
I can see the PDF file but when I like to print ist, I receive only a white page. 

Our Nextcloud installation ist up to date. 

Here is a list of our active apps:

Activity | 2.6.1
Brute-force settings | 1.0.3
Collaborative tags | 1.3.0
Comments | 1.3.0
Default encryption module | 2.0.0
Deleted files | 1.3.0
Federation | 1.3.0
File access control | 1.3.0
File sharing | 1.5.0
Files Right Click | 0.5.0
First run wizard | 2.2.1
Gallery | 18.0.0
Group folders | 1.2.0
Log Reader | 2.0.0
Monitoring | 1.3.0
Nextcloud announcements | 1.2.0
Notifications | 2.1.2
Password policy | 1.3.0
PDF viewer | 1.2.1
Share by mail | 1.3.0
Text editor | 2.5.1 
Theming | 1.4.1
Update notification | 1.3.0
Usage survey | 1.1.0
Versions | 1.6.0
Video player |  

Here is our config file:

  'instanceid' => 'XX',
  'passwordsalt' => 'XX',
  'secret' => 'XX',
  'trusted_domains' => 
  array (
    0 => 'sub.domain.tld',
  ),
  'datadirectory' => '/var/customers/webs/XXX/cloud/data',
  'overwrite.cli.url' => 'https://XXX',
  'dbtype' => 'mysql',
  'version' => '13.0.1.1',
  'dbname' => 'XXX',
  'dbhost' => 'XXX',
  'dbport' => '',
  'dbtableprefix' => 'XX',
  'dbuser' => 'XX',
  'dbpassword' => 'XX',
  'default_language' => 'de',
  'auth.bruteforce.protection.enabled' => true,
  'installed' => true,
  'mail_from_address' => 'intern',
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => 'sintetica.de',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'updater.secret' => 'XX',
  'theme' => '',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'appstoreenabled' => true,
  'enable_previews' => true,
  'skeletondirectory' => '',

We use a debian jessie sever with PHP 7.0

Thanks in advance for your Help.
Regards Michael

**Comment by 1tremer** [comment]
I forgot the browser safari

**Comment by 1tremer** [comment]
It works only with Firefox. 
I tried it with MS Explorer. Here I can see the correct PDF file but when I print it, then the layout is gone. 

Regards
Michael

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
