### ISSUE TITLE
Would be nice to grab focus on open for the pdf window

### ISSUE THREAD

**Issue by RNCTX** [nextcloud/files_pdfviewer#81]
### Steps to reproduce
1. open a pdf 
2. ctrl-f (or cmd-f on OSX)
3. no bueno, wrong search function trigger

### Expected behaviour
It would be nice if the pdfviewer window grabbed the cursor attention on load, so that ctrl-f with a PDF open would open the PDF.js text search box, rather than the Nextcloud search function
### Actual behaviour
Nextcloud search function opens unless the user clicks focus into the PDF first, before ctrl-f

### Server configuration

**Operating system**:
FreeBSD-11.1
**Web server:**
Nginx 1.12
**Database:**
Postgres 9.5
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
13.0.2
**Where did you install Nextcloud from:**
Official site zip file
**List of activated apps:**
Only relevant one is fulltextsearch_elasticsearch, same behavior comes from clicking on a search result there.

### Client configuration
**Browser:**
Chrome
**Operating system:**
OSX

**Comment by szaimen** [comment]
@skjnldsv I guess this is fixed as well by switching to viewer?
BTW: I think this is the last issue that I found that is potentially fixed by switching to viewer ;)

**Comment by skjnldsv** [comment]
Not fixed! But easily doable :)
https://github.com/nextcloud/files_pdfviewer/blob/7b2198f24b873f1fd7869c0e87add794fd5e4ebe/src/views/PDFView.vue#L41-L43

Add a vue `nextTick` and focus the iframe? Should work I think :thinking:

**Comment by szaimen** [comment]
@skjnldsv Do you mean something like this?
```
async mounted() { 
	this.doneLoading() 
	this.$nextTick(function () {
		this.focus()
	})
}, 
```

**Comment by skjnldsv** [comment]
> @skjnldsv Do you mean something like this?
> ```
> async mounted() { 
> 	this.doneLoading() 
> 	this.$nextTick(function () {
> 		this.focus()
> 	})
> }, 
> ```

Close, toi need to target the element.
So something like `this.$el.focus()`

**Comment by szaimen** [comment]
So than this?
```
async mounted() { 
	this.doneLoading() 
	this.$nextTick(function () {
		this.$el.focus()
	})
}, 
```
Alternatively this?
```
async mounted() { 
	this.doneLoading() 
	this.$nextTick(function () {
		const el = document.getElementsByName('PDFView')[0]
		this.el.focus()
	})
}, 
```

**Comment by skjnldsv** [comment]
> So than this?
> 
> ```
> async mounted() { 
> 	this.doneLoading() 
> 	this.$nextTick(function () {
> 		this.$el.focus()
> 	})
> }, 
> ```

Yes :)



> 		const el = document.getElementsByName('PDFView')[0]
> 		this.el.focus()

This is something to avoid, you can just add a ref to an element in vue
https://github.com/nextcloud/files_pdfviewer/blob/7b2198f24b873f1fd7869c0e87add794fd5e4ebe/src/views/PDFView.vue#L24

```vue
<iframe ref="iframe" :src="iframeSrc" />
```

then you can get it with `this.$refs.iframe.focus()` :wink:

**Comment by szaimen** [comment]
> > So than this?
> > ```
> > async mounted() { 
> > 	this.doneLoading() 
> > 	this.$nextTick(function () {
> > 		this.$el.focus()
> > 	})
> > }, 
> > ```
> 
> Yes :)

I mean this version seems simpler to me, so I am going with that. :)

Thanks for the help! I am going to open a PR with that fix.
