### ISSUE TITLE
Error generated in log

### ISSUE THREAD

**Issue by dgbrad** [nextcloud/files_pdfviewer#921]
The following error is generated in the log.
"sem_get(): Failed for key 0xa11: Permission denied at /home/bogus/www/next/lib/private/Preview/Generator.php#230"

**Comment by dgbrad** [comment]
Viewer seems to work, other than the 6-8 error messages placed in log on every use.

**Comment by joshtrichards** [comment]
Duplicate of nextcloud/server#44578

Likely a local environment issue. Some hints are in that Issue.
