### ISSUE TITLE
Feature request: Dual page without cover

### ISSUE THREAD

**Issue by kayila** [nextcloud/files_pdfviewer#96]
Some PDFs are designed with reading as a  dual paged where the first page starts on the left side. This us an issue in Nextcloud when that form of PDF has images that span both pages.

I would like to propose a seperation of view modes so dual page view becomes "dual + cover" and "dual without cover" which determines if the first page is a left page or right page.

**Comment by schniepp** [comment]
Currently, this PDF viewer does not allow for PDFs in dual page mode, correct? This is dearly missed!

**Comment by szaimen** [comment]
I think this is implemented by pdf.js and included in files_pdfciewer in the meantime
